# Generated by Django 5.2.4 on 2026-03-28 11:18

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', mysite.models.LowercaseCharField(db_index=True, max_length=2, unique=True)),
                ('label_obj', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': '00-01 Project Language',
                'ordering': ['language_id'],
            },
        ),
        migrations.CreateModel(
            name='ThemePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themepreset_id', mysite.models.LowercaseCharField(db_index=True, max_length=25, unique=True)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('primary', models.CharField(max_length=20)),
                ('secondary', models.CharField(max_length=20)),
                ('accent', models.CharField(max_length=20)),
                ('neutral', models.CharField(max_length=20)),
                ('primary_content', models.CharField(max_length=20)),
                ('secondary_content', models.CharField(max_length=20)),
                ('accent_content', models.CharField(max_length=20)),
                ('neutral_content', models.CharField(max_length=20)),
                ('base_100', models.CharField(max_length=20)),
                ('base_200', models.CharField(max_length=20)),
                ('base_300', models.CharField(max_length=20)),
                ('base_content', models.CharField(max_length=20)),
                ('success', models.CharField(max_length=20)),
                ('warning', models.CharField(max_length=20)),
                ('error', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=20)),
                ('success_content', models.CharField(max_length=20)),
                ('warning_content', models.CharField(max_length=20)),
                ('error_content', models.CharField(max_length=20)),
                ('info_content', models.CharField(max_length=20)),
                ('font_body', models.CharField(max_length=100)),
                ('font_heading', models.CharField(max_length=100)),
                ('base_font_size', models.CharField(default='16px', max_length=10)),
                ('scale_ratio', models.FloatField(default=1.2)),
                ('section_gap', models.CharField(default='4rem', max_length=10)),
                ('container_padding', models.CharField(default='1rem', max_length=10)),
                ('radius_btn', models.CharField(default='0.5rem', max_length=10)),
                ('radius_card', models.CharField(default='1rem', max_length=10)),
                ('radius_input', models.CharField(default='0.5rem', max_length=10)),
                ('shadow_sm', models.CharField(default='0 1px 2px 0 rgb(0 0 0 / 0.05)', max_length=50)),
                ('shadow_md', models.CharField(default='0 4px 6px -1px rgb(0 0 0 / 0.1)', max_length=50)),
                ('shadow_lg', models.CharField(default='0 10px 15px -3px rgb(0 0 0 / 0.1)', max_length=50)),
                ('is_system', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '00-02 Project ThemePresets',
                'ordering': ['themepreset_id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', mysite.models.LowercaseCharField(db_index=True, max_length=25, unique=True)),
                ('language_list', models.JSONField(blank=True, default=list, help_text='A JSON array of selected values from Language.', null=True)),
                ('theme_list', models.JSONField(blank=True, default=list, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.client')),
            ],
            options={
                'verbose_name': '00-03 Client',
                'ordering': ['client_id'],
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('level', models.PositiveSmallIntegerField(choices=[(10, 'Section'), (20, 'Row'), (30, 'Col'), (40, 'Cell')])),
                ('css_class', models.CharField(blank=True, max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('style', models.CharField(blank=True, max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('hidden', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.layout')),
            ],
            options={
                'verbose_name': '01-03 Layout',
                'ordering': ('page', 'level', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.CharField(choices=[('hero', 'Hero'), ('card', 'Card'), ('accordion', 'Accordion'), ('carousel', 'Carousel')], max_length=30)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('css_class', models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('card_body_class', models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('hero_content_class', models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('hero_overlay', models.BooleanField(default=False)),
                ('hero_overlay_style', models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('accordion_type', models.CharField(blank=True, max_length=25, null=True)),
                ('accordion_name', models.CharField(blank=True, max_length=25, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('hidden', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('layout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='component', to='mysite.layout')),
            ],
            options={
                'verbose_name': '01-04 Component L0',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', mysite.models.LowercaseCharField(max_length=10)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('order', models.PositiveIntegerField(default=0)),
                ('hidden', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='mysite.client')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.page')),
            ],
            options={
                'verbose_name': '01-02 Page',
                'ordering': ['client', 'order'],
            },
        ),
        migrations.AddField(
            model_name='layout',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='mysite.page'),
        ),
        migrations.CreateModel(
            name='TextstbItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('item_id', models.CharField(choices=[('text', 'Text'), ('svg', 'SVG'), ('badge', 'Badge')], max_length=20)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('hidden', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('svg_text', models.CharField(blank=True, max_length=500, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '01-06b Text SVG/Text/Badge item',
            },
        ),
        migrations.CreateModel(
            name='SvgtextbadgeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stext', models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('ltext', models.TextField(blank=True, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.language')),
                ('textstbitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.textstbitem')),
            ],
            options={
                'verbose_name': '01-06c Svg Text Badge(STB) Item value',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_id', mysite.models.LowercaseCharField(max_length=10)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('order', models.PositiveIntegerField(default=0)),
                ('hidden', models.BooleanField(default=False)),
                ('overrides', models.JSONField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='mysite.client')),
                ('themepreset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.themepreset')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ComponentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('figure', 'Figure'), ('text', 'Text')], max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('hidden', models.BooleanField(default=False)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('css_class', models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('figure_class', models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('actions_class', models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('accordion_checked', models.BooleanField(default=False)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='mysite.component')),
            ],
            options={
                'verbose_name': '01-05 Component L1 Slot',
                'ordering': ['component', 'order'],
                'unique_together': {('component', 'slot_type', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ComptextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('block_id', models.CharField(choices=[('title', 'Title'), ('content', 'Content'), ('actbut', 'ActionButtons')], max_length=20)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('hidden', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('css_class', models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('href_page', models.CharField(blank=True, max_length=25, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '01-06a Component Text Block',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='mysite_comp_content_8337a2_idx'), models.Index(fields=['content_type', 'object_id', 'order'], name='mysite_comp_content_a5210d_idx')],
                'unique_together': {('content_type', 'object_id', 'block_id', 'order')},
            },
        ),
        migrations.CreateModel(
            name='GentextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('block_id', models.CharField(choices=[('name', 'Name'), ('nb_title', 'Navbar Title'), ('nb_subtitle', 'Navbar SubTitle')], max_length=20)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('hidden', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('css_class', models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '01-06a General Text Block',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='mysite_gent_content_4f86bd_idx'), models.Index(fields=['content_type', 'object_id', 'order'], name='mysite_gent_content_042b5b_idx')],
                'unique_together': {('content_type', 'object_id', 'block_id', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['client', 'order'], name='mysite_page_client__5798a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('client', 'page_id')},
        ),
        migrations.AlterUniqueTogether(
            name='layout',
            unique_together={('page', 'level', 'slug')},
        ),
        migrations.AddIndex(
            model_name='textstbitem',
            index=models.Index(fields=['content_type', 'object_id'], name='mysite_text_content_5b3e70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='textstbitem',
            unique_together={('content_type', 'object_id', 'item_id', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='svgtextbadgevalue',
            unique_together={('textstbitem', 'language')},
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['client', 'order'], name='mysite_them_client__fae9d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together={('client', 'theme_id')},
        ),
    ]
