# Generated by Django 5.2.4 on 2026-01-02 11:19

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', mysite.models.LowercaseCharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': '00-03 Project Language',
                'ordering': ['language_id'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_id', mysite.models.LowercaseCharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': '00-04 Project Theme',
                'ordering': ['theme_id'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', mysite.models.LowercaseCharField(max_length=20, unique=True)),
                ('ltext', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': '00-02 Token',
            },
        ),
        migrations.CreateModel(
            name='TokenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokentype_id', mysite.models.LowercaseCharField(max_length=20, unique=True)),
                ('ltext', models.CharField(max_length=50, null=True)),
                ('is_global', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '00-01 Token Type2',
                'ordering': ['tokentype_id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', mysite.models.LowercaseCharField(max_length=25, unique=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_client_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.client', to_field='client_id')),
            ],
            options={
                'verbose_name': '00-05 Client',
                'ordering': ['client_id'],
            },
        ),
        migrations.CreateModel(
            name='ClientLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_languages_rel', to='mysite.client', to_field='client_id')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_clients_rel', to='mysite.language', to_field='language_id')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('client', 'language')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='client_languages',
            field=models.ManyToManyField(related_name='clients', through='mysite.ClientLanguage', to='mysite.language'),
        ),
        migrations.CreateModel(
            name='ClientTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_themes_rel', to='mysite.client', to_field='client_id')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_clients_rel', to='mysite.theme', to_field='theme_id')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('client', 'theme')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='client_themes',
            field=models.ManyToManyField(related_name='clients', through='mysite.ClientTheme', to='mysite.theme'),
        ),
        migrations.AddField(
            model_name='theme',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='mysite.token', to_field='token_id'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', mysite.models.LowercaseCharField(max_length=10, unique=True)),
                ('token', models.ForeignKey(default='page_name', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='mysite.token', to_field='token_id')),
            ],
            options={
                'verbose_name': '00-04 Project Page',
                'ordering': ['page_id'],
            },
        ),
        migrations.AddField(
            model_name='language',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='mysite.token', to_field='token_id'),
        ),
        migrations.AddField(
            model_name='client',
            name='token',
            field=models.ForeignKey(default='client_name', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='mysite.token', to_field='token_id'),
        ),
        migrations.AddField(
            model_name='token',
            name='tokentype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='mysite.tokentype', to_field='tokentype_id'),
        ),
        migrations.CreateModel(
            name='TextStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mysite.client', to_field='client_id')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mysite.language', to_field='language_id')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mysite.page', to_field='page_id')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mysite.token', to_field='token_id')),
            ],
            options={
                'verbose_name': '00-06 TextStatic',
                'unique_together': {('client', 'token', 'language', 'page')},
            },
        ),
    ]
