# Generated by Django 5.2.4 on 2026-01-31 11:17

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltext', models.CharField(blank=True, max_length=50, null=True)),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('body_class', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '01-05b Card',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css_class', models.CharField(blank=True, max_length=255)),
                ('herocontent_class', models.CharField(blank=True, max_length=255)),
                ('overlay', models.BooleanField(default=False)),
                ('overlay_style', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': '01-05a Hero',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', mysite.models.LowercaseCharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': '00-03 Project Language',
                'ordering': ['language_id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', mysite.models.LowercaseCharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': '00-04 Project Page',
                'ordering': ['page_id'],
            },
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(choices=[('title', 'Title'), ('content', 'Content'), ('actbut', 'ActionButtons')], max_length=20)),
                ('ltext', models.CharField(max_length=50, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_id', mysite.models.LowercaseCharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': '00-04 Project Theme',
                'ordering': ['theme_id'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', mysite.models.LowercaseCharField(max_length=20, unique=True)),
                ('ltext', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': '00-02 Token',
            },
        ),
        migrations.CreateModel(
            name='TokenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokentype_id', mysite.models.LowercaseCharField(max_length=20, unique=True)),
                ('ltext', models.CharField(max_length=50, null=True)),
                ('is_global', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '00-01 Token Type2',
                'ordering': ['tokentype_id'],
            },
        ),
        migrations.CreateModel(
            name='CardFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltext', models.CharField(blank=True, max_length=50, null=True)),
                ('figure_class', models.CharField(blank=True, max_length=255, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('position_id', models.CharField(blank=True, choices=[('start', 'Start'), ('end', 'End')], max_length=20, null=True)),
                ('image_url', models.URLField(max_length=500)),
                ('alt', models.CharField(default='Default', max_length=100)),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cardfigure', to='mysite.card')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', mysite.models.LowercaseCharField(max_length=25, unique=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_client_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.client', to_field='client_id')),
            ],
            options={
                'verbose_name': '00-05 Client',
                'ordering': ['client_id'],
            },
        ),
        migrations.CreateModel(
            name='HeroCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('hidden', models.BooleanField(default=False)),
                ('type_id', models.CharField(default='card', max_length=10)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True)),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('body_class', models.CharField(blank=True, max_length=255, null=True)),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='herocard', to='mysite.hero')),
            ],
            options={
                'verbose_name': '01-05a3 HeroCard',
                'unique_together': {('hero', 'type_id')},
            },
        ),
        migrations.CreateModel(
            name='HeroCardFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltext', models.CharField(blank=True, max_length=50, null=True)),
                ('figure_class', models.CharField(blank=True, max_length=255, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('position_id', models.CharField(blank=True, choices=[('start', 'Start'), ('end', 'End')], max_length=20, null=True)),
                ('image_url', models.URLField(max_length=500)),
                ('alt', models.CharField(default='Default', max_length=100)),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('herocard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='herocardfigure', to='mysite.herocard')),
            ],
            options={
                'verbose_name': '01-05a3b HeroCard Figure',
            },
        ),
        migrations.CreateModel(
            name='ClientLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_languages_rel', to='mysite.client', to_field='client_id')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_clients_rel', to='mysite.language', to_field='language_id')),
            ],
            options={
                'verbose_name': '01-01 Client Language',
                'ordering': ['client', 'order'],
                'unique_together': {('client', 'language')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='client_languages',
            field=models.ManyToManyField(related_name='clients', through='mysite.ClientLanguage', to='mysite.language'),
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('level', models.PositiveSmallIntegerField(choices=[(10, 'Section'), (20, 'Row'), (30, 'Col'), (40, 'Cell')])),
                ('css_class', models.CharField(blank=True, max_length=255)),
                ('style', models.CharField(blank=True, max_length=255)),
                ('hidden', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
                ('comp_id', models.CharField(blank=True, choices=[('hero', 'Comp Hero'), ('card', 'Comp Card'), ('accordion', 'Comp Accordion'), ('carousel', 'Comp Carousel')], max_length=30, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.client', to_field='client_id')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layoutchildren', to='mysite.layout')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.page', to_field='page_id')),
            ],
            options={
                'verbose_name': '01-04 Layout',
                'ordering': ('client', 'page', 'level', 'order'),
                'unique_together': {('client', 'page', 'level', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='hero',
            name='layout',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='mysite.layout'),
        ),
        migrations.AddField(
            model_name='card',
            name='layout',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='mysite.layout'),
        ),
        migrations.CreateModel(
            name='TextBlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(choices=[('text', 'Text'), ('svg', 'SVG'), ('badge', 'Badge')], max_length=20)),
                ('ltext', models.CharField(max_length=50, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('svg_text', models.CharField(blank=True, max_length=500, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mysite.textblock')),
            ],
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('ltext', models.CharField(max_length=50, null=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='textblock',
            name='textcontent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='mysite.textcontent'),
        ),
        migrations.CreateModel(
            name='HeroCardText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltext', models.CharField(blank=True, max_length=50, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('actions_class', models.CharField(blank=True, max_length=255, null=True)),
                ('actions_position_id', models.CharField(blank=True, choices=[('start', 'Start'), ('end', 'End')], max_length=20, null=True)),
                ('herocard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='herocardtext', to='mysite.herocard')),
                ('textcontent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.textcontent')),
            ],
            options={
                'verbose_name': '01-05a3a HeroCard Text',
            },
        ),
        migrations.CreateModel(
            name='CardText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltext', models.CharField(max_length=50, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('actions_class', models.CharField(blank=True, max_length=255, null=True)),
                ('actions_position_id', models.CharField(blank=True, choices=[('start', 'Start'), ('end', 'End')], max_length=20, null=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cardtext', to='mysite.card')),
                ('textcontent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.textcontent')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_themes_rel', to='mysite.client', to_field='client_id')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_clients_rel', to='mysite.theme', to_field='theme_id')),
            ],
            options={
                'verbose_name': '01-02 Client Theme',
                'ordering': ['client', 'order'],
                'unique_together': {('client', 'theme')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='client_themes',
            field=models.ManyToManyField(related_name='clients', through='mysite.ClientTheme', to='mysite.theme'),
        ),
        migrations.AddField(
            model_name='theme',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='mysite.token', to_field='token_id'),
        ),
        migrations.AddField(
            model_name='page',
            name='token',
            field=models.ForeignKey(default='page_name', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='mysite.token', to_field='token_id'),
        ),
        migrations.AddField(
            model_name='language',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='mysite.token', to_field='token_id'),
        ),
        migrations.AddField(
            model_name='client',
            name='token',
            field=models.ForeignKey(default='client_name', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='mysite.token', to_field='token_id'),
        ),
        migrations.AddField(
            model_name='token',
            name='tokentype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='mysite.tokentype'),
        ),
        migrations.CreateModel(
            name='HeroFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('hidden', models.BooleanField(default=False)),
                ('type_id', models.CharField(default='figure', max_length=10)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True)),
                ('figure_class', models.CharField(blank=True, max_length=255, null=True)),
                ('position_id', models.CharField(blank=True, choices=[('start', 'Start'), ('end', 'End')], max_length=20, null=True)),
                ('image_url', models.URLField(max_length=500)),
                ('alt', models.CharField(default='Default', max_length=100)),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='herofigure', to='mysite.hero')),
            ],
            options={
                'verbose_name': '01-05a2 HeroFigure',
                'unique_together': {('hero', 'type_id')},
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', mysite.models.LowercaseCharField(max_length=25)),
                ('image_url', models.URLField(max_length=500)),
                ('alt', models.CharField(max_length=100)),
                ('client', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mysite.client', to_field='client_id')),
                ('page', models.ForeignKey(default='global', on_delete=django.db.models.deletion.CASCADE, to='mysite.page', to_field='page_id')),
            ],
            options={
                'verbose_name': '00-07 Image',
                'indexes': [models.Index(fields=['image_id', 'client'], name='mysite_imag_image_i_ae4806_idx')],
                'unique_together': {('client', 'image_id', 'page')},
            },
        ),
        migrations.CreateModel(
            name='ClientPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_unique', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_page', to='mysite.client', to_field='client_id')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.clientpage')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_page', to='mysite.page', to_field='page_id')),
            ],
            options={
                'verbose_name': '01-03 Client Pages',
                'ordering': ['client', 'order'],
                'unique_together': {('client', 'page')},
            },
        ),
        migrations.CreateModel(
            name='Svg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_id', mysite.models.LowercaseCharField(max_length=25)),
                ('svg_text', models.CharField(max_length=500)),
                ('client', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='svgs', to='mysite.client', to_field='client_id')),
                ('page', models.ForeignKey(default='global', on_delete=django.db.models.deletion.CASCADE, to='mysite.page', to_field='page_id')),
            ],
            options={
                'verbose_name': '00-08 Svg',
                'indexes': [models.Index(fields=['svg_id', 'client'], name='mysite_svg_svg_id_0d38e5_idx')],
                'unique_together': {('client', 'svg_id', 'page')},
            },
        ),
        migrations.CreateModel(
            name='TextBlockItemValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='mysite.textblockitem')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.language')),
            ],
            options={
                'unique_together': {('item', 'language')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='textblock',
            unique_together={('textcontent', 'block_id')},
        ),
        migrations.CreateModel(
            name='HeroText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('hidden', models.BooleanField(default=False)),
                ('type_id', models.CharField(default='text', max_length=10)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True)),
                ('actions_class', models.CharField(blank=True, max_length=255, null=True)),
                ('actions_position_id', models.CharField(blank=True, choices=[('start', 'Start'), ('end', 'End')], max_length=20, null=True)),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='herotext', to='mysite.hero')),
                ('textcontent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.textcontent')),
            ],
            options={
                'verbose_name': '01-05a1 HeroText',
                'unique_together': {('hero', 'type_id')},
            },
        ),
        migrations.CreateModel(
            name='TextStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mysite.client', to_field='client_id')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mysite.language', to_field='language_id')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mysite.page', to_field='page_id')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mysite.token', to_field='token_id')),
            ],
            options={
                'verbose_name': '00-06 TextStatic',
                'indexes': [models.Index(fields=['client'], name='mysite_text_client__288926_idx')],
                'unique_together': {('client', 'token', 'language', 'page')},
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_id'], name='mysite_clie_client__fe9101_idx'),
        ),
    ]
