# Generated by Django 5.2.4 on 2026-01-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_id'], name='mysite_clie_client__fe9101_idx'),
        ),
        migrations.AddIndex(
            model_name='textstatic',
            index=models.Index(fields=['client'], name='mysite_text_client__288926_idx'),
        ),
    ]
