# Generated by Django 5.2.4 on 2026-02-02 07:07

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', mysite.models.LowercaseCharField(max_length=2, unique=True)),
                ('label_obj', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': '00-01 Project Language2',
                'ordering': ['language_id'],
            },
        ),
        migrations.CreateModel(
            name='Theme2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_id', mysite.models.LowercaseCharField(max_length=2, unique=True)),
                ('label_obj', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': '00-02 Project Theme2',
                'ordering': ['theme_id'],
            },
        ),
        migrations.CreateModel(
            name='TextItemValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('stext', models.CharField(blank=True, max_length=255, null=True)),
                ('ltext', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.language2')),
            ],
        ),
    ]
