# Generated by Django 5.2.4 on 2025-12-31 07:37

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', mysite.models.LowercaseCharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': '00-03 Project Language2',
                'ordering': ['language_id'],
            },
        ),
        migrations.CreateModel(
            name='Theme2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_id', mysite.models.LowercaseCharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': '00-04 Project Theme2',
                'ordering': ['theme_id'],
            },
        ),
        migrations.CreateModel(
            name='Token2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', mysite.models.LowercaseCharField(max_length=20, unique=True)),
                ('ltext', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': '00-02 Token2',
            },
        ),
        migrations.CreateModel(
            name='TokenType2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokentype_id', mysite.models.LowercaseCharField(max_length=20, unique=True)),
                ('ltext', models.CharField(max_length=50, null=True)),
                ('is_global', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '00-01 Token Type2',
                'ordering': ['tokentype_id'],
            },
        ),
        migrations.CreateModel(
            name='Client2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', mysite.models.LowercaseCharField(max_length=25, unique=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_client_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.client2', to_field='client_id')),
            ],
            options={
                'verbose_name': '00-05 Client2',
                'ordering': ['client_id'],
            },
        ),
        migrations.CreateModel(
            name='ClientLanguage2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_languages_rel', to='mysite.client2', to_field='client_id')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_clients_rel', to='mysite.language2', to_field='language_id')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('client', 'language')},
            },
        ),
        migrations.AddField(
            model_name='client2',
            name='client_languages2',
            field=models.ManyToManyField(related_name='clients', through='mysite.ClientLanguage2', to='mysite.language2'),
        ),
        migrations.CreateModel(
            name='ClientTheme2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_themes_rel', to='mysite.client2', to_field='client_id')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_clients_rel', to='mysite.theme2', to_field='theme_id')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('client', 'theme')},
            },
        ),
        migrations.AddField(
            model_name='client2',
            name='client_themes2',
            field=models.ManyToManyField(related_name='clients', through='mysite.ClientTheme2', to='mysite.theme2'),
        ),
        migrations.AddField(
            model_name='theme2',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='mysite.token2', to_field='token_id'),
        ),
        migrations.CreateModel(
            name='Page2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', mysite.models.LowercaseCharField(max_length=10, unique=True)),
                ('token', models.ForeignKey(default='page_name', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='mysite.token2', to_field='token_id')),
            ],
            options={
                'verbose_name': '00-04 Project Page2',
                'ordering': ['page_id'],
            },
        ),
        migrations.AddField(
            model_name='language2',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='mysite.token2', to_field='token_id'),
        ),
        migrations.AddField(
            model_name='client2',
            name='token',
            field=models.ForeignKey(default='client_name', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='mysite.token2', to_field='token_id'),
        ),
        migrations.AddField(
            model_name='token2',
            name='tokentype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='mysite.tokentype2', to_field='tokentype_id'),
        ),
        migrations.CreateModel(
            name='Translation2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mysite.client2', to_field='client_id')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mysite.language2', to_field='language_id')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mysite.page2', to_field='page_id')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mysite.token2', to_field='token_id')),
            ],
            options={
                'verbose_name': '00-06 Translation2',
                'unique_together': {('client', 'token', 'language', 'page')},
            },
        ),
    ]
