# Generated by Django 5.2.4 on 2025-09-04 07:20

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maxlanguage',
            options={'verbose_name': '00-00 Maximum Project Language'},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': '00-02 Token'},
        ),
        migrations.AlterModelOptions(
            name='tokentype',
            options={'verbose_name': '00-01 Token Type'},
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id_language', mysite.models.LowercaseCharField(max_length=2, primary_key=True, serialize=False)),
                ('language_name_token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.token')),
            ],
            options={
                'verbose_name': '00-03 Project Language',
            },
        ),
    ]
