# Generated by Django 5.2.4 on 2026-04-01 06:54

import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nb_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nb_title_svg_pre',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='nb_title_svg_suf',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='language_list',
            field=models.JSONField(blank=True, default=mysite.models.default_languages, help_text='A JSON array of selected values from Language.', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='theme_list',
            field=models.JSONField(blank=True, default=mysite.models.default_themes, null=True),
        ),
    ]
