# Generated by Django 5.2.4 on 2026-02-06 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_layout_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.client'),
        ),
    ]
