# Generated by Django 5.2.4 on 2026-01-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_language2_theme2_token2_tokentype2_client2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Translation2',
            new_name='TextStatic2',
        ),
        migrations.AlterModelOptions(
            name='textstatic2',
            options={'verbose_name': '00-06 TextStatic2'},
        ),
    ]
