# Generated by Django 5.2.4 on 2026-02-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mysite', '0002_language2_theme2_textitemvalue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextItemValue',
            new_name='TextItemValue2',
        ),
    ]
