# Generated by Django 5.2.4 on 2026-01-03 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_client_mysite_clie_client__fe9101_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNavbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_navbar_rel', to='mysite.client', to_field='client_id')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_navbar_rel', to='mysite.page', to_field='page_id')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.clientnavbar')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('client', 'page')},
            },
        ),
    ]
