# Generated by Django 5.2.4 on 2025-09-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_maxlanguage_options_alter_token_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='language_name_token',
        ),
    ]
