# Generated by Django 5.2.4 on 2026-02-02 07:37

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_rename_textitemvalue_textitemvalue2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', mysite.models.LowercaseCharField(max_length=25, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.client2')),
            ],
        ),
    ]
