# Generated by Django 5.2.4 on 2025-09-04 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_remove_language_language_name_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='language_name_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.token'),
        ),
    ]
