# Generated by Django 5.2.4 on 2026-04-05 11:07

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_client_name_en_client_name_fr_client_name_hi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalValCat',
            fields=[
                ('globalvalcat_id', mysite.models.LowercaseCharField(max_length=25, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Global Value Category',
                'verbose_name_plural': 'Global Value Categories',
                'ordering': ['globalvalcat_id'],
            },
        ),
        migrations.CreateModel(
            name='GlobalVal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('keyval', models.CharField(max_length=500)),
                ('keyval_en', models.CharField(max_length=500, null=True)),
                ('keyval_hi', models.CharField(max_length=500, null=True)),
                ('keyval_fr', models.CharField(max_length=500, null=True)),
                ('keyval_ta', models.CharField(max_length=500, null=True)),
                ('globalvalcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='globalvals', to='mysite.globalvalcat')),
            ],
            options={
                'ordering': ['globalvalcat__globalvalcat_id', 'key'],
                'unique_together': {('globalvalcat', 'key')},
            },
        ),
    ]
