# Generated by Django 5.2.4 on 2026-01-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_rename_translation2_textstatic2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienttheme',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientlanguage',
            name='client',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='client',
        ),
        migrations.AlterUniqueTogether(
            name='clientlanguage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clientlanguage',
            name='language',
        ),
        migrations.AlterUniqueTogether(
            name='clienttheme',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clienttheme',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='language',
            name='token',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='language',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='token',
        ),
        migrations.RemoveField(
            model_name='token',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='token',
            name='tokentype',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='token',
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientLanguage',
        ),
        migrations.DeleteModel(
            name='ClientTheme',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.DeleteModel(
            name='TokenType',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
