# Generated by Django 5.2.4 on 2026-01-13 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_clientnavbar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientlanguage',
            options={'ordering': ['client', 'order'], 'verbose_name': '01-01 Client Language'},
        ),
        migrations.AlterModelOptions(
            name='clienttheme',
            options={'ordering': ['client', 'order'], 'verbose_name': '01-02 Client Theme'},
        ),
        migrations.CreateModel(
            name='ClientNavbar2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_page', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_navbar2_rel', to='mysite.client', to_field='client_id')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_navbar2_rel', to='mysite.page', to_field='page_id')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_client_page', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children2', to='mysite.clientnavbar2', to_field='client_page')),
            ],
            options={
                'verbose_name': '01-03 Client Navbar item2',
                'ordering': ['client', 'order'],
                'unique_together': {('client', 'page')},
            },
        ),
        migrations.DeleteModel(
            name='ClientNavbar',
        ),
    ]
