# Generated by Django 5.2.4 on 2026-02-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_layout_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtext',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='textblockitem',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
