# Generated by Django 5.2.4 on 2026-04-06 04:48

import mysite.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_globalvalcat_globalval'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='svgtextbadgevalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='svgtextbadgevalue',
            name='language2_id',
            field=mysite.models.LowercaseCharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='svgtextbadgevalue',
            unique_together={('textstbitem', 'language', 'language2_id')},
        ),
    ]
