# Generated by Django 5.2.4 on 2026-02-06 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_cardtext_ltext_alter_page_ltext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='mysite.page'),
        ),
    ]
