# Generated by Django 5.2.4 on 2025-09-04 07:58

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_language_language_name_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='parent_id',
            new_name='id_parent',
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id_theme', mysite.models.LowercaseCharField(max_length=20, primary_key=True, serialize=False)),
                ('theme_name_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.token')),
            ],
            options={
                'verbose_name': '00-04 Project Theme',
            },
        ),
    ]
