# Generated by Django 5.2.4 on 2026-02-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_client2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client2',
            options={'ordering': ['client_id'], 'verbose_name': '00-03 Client2'},
        ),
        migrations.AddField(
            model_name='client2',
            name='language_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='client2',
            name='theme_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
