# Generated by Django 5.2.4 on 2026-04-06 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_svgtextbadgevalue_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='svgtextbadgevalue',
            old_name='language2_id',
            new_name='language_code',
        ),
        migrations.AlterUniqueTogether(
            name='svgtextbadgevalue',
            unique_together={('textstbitem', 'language', 'language_code')},
        ),
    ]
