# Generated by Django 5.2.4 on 2026-01-14 06:04

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_clientnavbar_delete_clientnavbar2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', mysite.models.LowercaseCharField(max_length=25)),
                ('image_url', models.URLField(max_length=500)),
                ('alt', models.CharField(max_length=100)),
                ('client', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mysite.client', to_field='client_id')),
                ('page', models.ForeignKey(default='global', on_delete=django.db.models.deletion.CASCADE, to='mysite.page', to_field='page_id')),
            ],
            options={
                'verbose_name': '00-07 ImageStatic',
                'indexes': [models.Index(fields=['image_id', 'client'], name='mysite_imag_image_i_0c3e67_idx')],
                'unique_together': {('client', 'image_id', 'page')},
            },
        ),
    ]
