# Generated by Django 5.2.4 on 2026-02-03 07:25

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_client2_options_client2_language_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client2',
            name='language_list',
            field=models.JSONField(blank=True, default=list, help_text='A JSON array of selected values from Language.', null=True),
        ),
        migrations.CreateModel(
            name='Page2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', mysite.models.LowercaseCharField(max_length=10, unique=True)),
                ('ltext', models.CharField(max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='mysite.client2')),
            ],
            options={
                'ordering': ['page_id'],
            },
        ),
    ]
