# Generated by Django 5.2.4 on 2025-09-04 08:36

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_rename_parent_id_token_id_parent_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', mysite.models.LowercaseCharField(max_length=25, primary_key=True, serialize=False)),
                ('client_languages', models.ManyToManyField(blank=True, related_name='clients', to='mysite.language')),
                ('client_name_token', models.ForeignKey(blank=True, default='g_client_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.token')),
                ('client_themes', models.ManyToManyField(blank=True, related_name='clients', to='mysite.theme')),
                ('id_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mysite.client')),
            ],
        ),
    ]
