# Generated by Django 5.2.4 on 2026-02-08 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_layout_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('level', models.PositiveSmallIntegerField(choices=[(10, 'Section'), (20, 'Row'), (30, 'Col'), (40, 'Cell')])),
                ('css_class', models.CharField(blank=True, max_length=255)),
                ('style', models.CharField(blank=True, max_length=255)),
                ('hidden', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
                ('comp_id', models.CharField(blank=True, choices=[('hero', 'Comp Hero'), ('card', 'Comp Card'), ('accordion', 'Comp Accordion'), ('carousel', 'Comp Carousel')], max_length=30, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts2', to='mysite.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layoutchildren', to='mysite.layout2')),
            ],
            options={
                'verbose_name': '01-04 Layout2',
                'ordering': ('page', 'level', 'order'),
                'unique_together': {('page', 'level', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Hero2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css_class', models.CharField(blank=True, max_length=255)),
                ('herocontent_class', models.CharField(blank=True, max_length=255)),
                ('overlay', models.BooleanField(default=False)),
                ('overlay_style', models.CharField(blank=True, max_length=255)),
                ('layout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='mysite.layout2')),
            ],
            options={
                'verbose_name': '01-05a Hero2',
            },
        ),
        migrations.CreateModel(
            name='Card2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltext', models.CharField(blank=True, max_length=50, null=True)),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('body_class', models.CharField(blank=True, max_length=255, null=True)),
                ('layout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='mysite.layout2')),
            ],
            options={
                'verbose_name': '01-05b Card2',
            },
        ),
    ]
