# Generated by Django 5.2.4 on 2026-02-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_layout2_hero2_card2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero2',
            name='layout',
        ),
        migrations.AlterUniqueTogether(
            name='layout2',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='layout2',
            name='page',
        ),
        migrations.RemoveField(
            model_name='layout2',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Card2',
        ),
        migrations.DeleteModel(
            name='Hero2',
        ),
        migrations.DeleteModel(
            name='Layout2',
        ),
    ]
