# Generated by Django 5.2.4 on 2025-09-04 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': '00-05 Client'},
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mysite.client')),
                ('id_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.language')),
                ('id_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='mysite.token')),
            ],
            options={
                'verbose_name': '00-06 Translation',
                'unique_together': {('id_client', 'id_token', 'id_language')},
            },
        ),
    ]
