# Generated by Django 5.2.4 on 2026-04-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_rename_language2_id_svgtextbadgevalue_language_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='svgtextbadgevalue',
            old_name='language',
            new_name='zzlanguage',
        ),
        migrations.AlterUniqueTogether(
            name='svgtextbadgevalue',
            unique_together={('textstbitem', 'language_code')},
        ),
    ]
