# Generated by Django 5.2.4 on 2026-01-14 08:05

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_imagestatic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SvgStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_id', mysite.models.LowercaseCharField(max_length=25)),
                ('svg_text', models.CharField(max_length=500)),
                ('client', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='svgs', to='mysite.client', to_field='client_id')),
                ('page', models.ForeignKey(default='global', on_delete=django.db.models.deletion.CASCADE, to='mysite.page', to_field='page_id')),
            ],
            options={
                'verbose_name': '00-08 SvgStatic',
                'indexes': [models.Index(fields=['svg_id', 'client'], name='mysite_svgs_svg_id_de0f06_idx')],
                'unique_together': {('client', 'svg_id', 'page')},
            },
        ),
    ]
