# Generated by Django 5.2.4 on 2026-02-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mysite', '0007_page2_hidden_page2_order_page2_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page2',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='textitemvalue2',
            unique_together={('content_type', 'object_id', 'language')},
        ),
    ]
