# Generated by Django 5.2.4 on 2025-09-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_client_options_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_languages',
            field=models.ManyToManyField(blank=True, related_name='clients_old', to='mysite.language'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_themes',
            field=models.ManyToManyField(blank=True, related_name='clients_old', to='mysite.theme'),
        ),
    ]
