# Generated by Django 5.2.4 on 2026-04-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_rename_language_svgtextbadgevalue_zzlanguage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svgtextbadgevalue',
            name='zzlanguage',
        ),
        migrations.AlterModelOptions(
            name='globalvalcat',
            options={'ordering': ['globalvalcat_id'], 'verbose_name': '00-01 Project Global Value Category'},
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
