# Generated by Django 5.2.4 on 2026-02-15 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mysite', '0007_remove_hero2_layout_alter_layout2_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComptextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('block_id', models.CharField(choices=[('title', 'Title'), ('content', 'Content'), ('actbut', 'ActionButtons')], max_length=20)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('content_type', 'object_id', 'block_id', 'order')},
            },
        ),
        migrations.CreateModel(
            name='GentextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('block_id', models.CharField(choices=[('name', 'Name'), ('nb_title', 'Navbar Title'), ('nb_subtitle', 'Navbar SubTitle')], max_length=20)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('content_type', 'object_id', 'block_id', 'order')},
            },
        ),
        migrations.CreateModel(
            name='TextstbItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('item_id', models.CharField(choices=[('text', 'Text'), ('svg', 'SVG'), ('badge', 'Badge')], max_length=20)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('svg_text', models.CharField(blank=True, max_length=500, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('content_type', 'object_id', 'item_id', 'order')},
            },
        ),
    ]
