# Generated by Django 5.2.4 on 2026-01-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_clientnavbar2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientNavbar',
        ),
    ]
