# Generated by Django 5.2.4 on 2026-04-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_remove_svgtextbadgevalue_zzlanguage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalvalcat',
            options={'ordering': ['globalvalcat_id'], 'verbose_name': '00-01 Project Global Value Category', 'verbose_name_plural': '00-01 Project Global Value Categories'},
        ),
        migrations.AlterModelOptions(
            name='themepreset',
            options={'ordering': ['themepreset_id'], 'verbose_name': '00-02 Project ThemePreset'},
        ),
    ]
