# Generated by Django 5.2.4 on 2026-02-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_comptextblock_gentextblock_textstbitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comptextblock',
            options={'verbose_name': '01-06a Component Text Block'},
        ),
        migrations.AlterModelOptions(
            name='gentextblock',
            options={'verbose_name': '01-06a General Text Block'},
        ),
        migrations.AlterModelOptions(
            name='textblock',
            options={'verbose_name': '01-06b Text Block'},
        ),
        migrations.AlterModelOptions(
            name='textblockitem',
            options={'verbose_name': '01-06c Text Block Item'},
        ),
        migrations.AlterModelOptions(
            name='textcontent',
            options={'verbose_name': '01-06a Text Content'},
        ),
        migrations.AlterModelOptions(
            name='textitemvalue',
            options={'verbose_name': '01-06d Text Item value'},
        ),
        migrations.AlterModelOptions(
            name='textstbitem',
            options={'verbose_name': '01-06b Text SVG/Text/Badge item'},
        ),
        migrations.AlterUniqueTogether(
            name='textstbitem',
            unique_together=set(),
        ),
    ]
