# Generated by Django 5.2.4 on 2025-09-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_client_client_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_languages',
            field=models.ManyToManyField(blank=True, related_name='clients', to='mysite.language'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_themes',
            field=models.ManyToManyField(blank=True, related_name='clients', to='mysite.theme'),
        ),
    ]
