# Generated by Django 5.2.4 on 2026-04-07 04:52

import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_globalvalcat_options_alter_themepreset_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='card_body_class',
            field=models.CharField(blank=True, default='', max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='css_class',
            field=models.CharField(blank=True, default='', max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='hero_content_class',
            field=models.CharField(blank=True, default='', max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='hero_overlay_style',
            field=models.CharField(blank=True, default='', max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='ltext',
            field=models.CharField(blank=True, default='', max_length=50, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componentslot',
            name='actions_class',
            field=models.CharField(blank=True, default='', max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componentslot',
            name='css_class',
            field=models.CharField(blank=True, default='', max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componentslot',
            name='figure_class',
            field=models.CharField(blank=True, default='', max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componentslot',
            name='ltext',
            field=models.CharField(blank=True, default='', max_length=50, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comptextblock',
            name='css_class',
            field=models.CharField(blank=True, default='', max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comptextblock',
            name='ltext',
            field=models.CharField(blank=True, default='', max_length=50, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gentextblock',
            name='css_class',
            field=models.CharField(blank=True, default='', max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gentextblock',
            name='ltext',
            field=models.CharField(blank=True, default='', max_length=50, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='ltext',
            field=models.CharField(blank=True, default='', max_length=50, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='svgtextbadgevalue',
            name='language_code',
            field=mysite.models.LowercaseCharField(blank=True, default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='svgtextbadgevalue',
            name='ltext',
            field=models.TextField(blank=True, default='', validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='svgtextbadgevalue',
            name='stext',
            field=models.CharField(blank=True, default='', max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textstbitem',
            name='ltext',
            field=models.CharField(blank=True, default='', max_length=50, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='ltext',
            field=models.CharField(blank=True, default='', max_length=50, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='themepreset',
            name='ltext',
            field=models.CharField(blank=True, default='', max_length=50, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
            preserve_default=False,
        ),
    ]
