# Generated by Django 5.2.4 on 2026-02-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_comptextblock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptextblock',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gentextblock',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='textstbitem',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
