# Generated by Django 5.2.4 on 2025-09-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_client_client_languages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_languages',
            new_name='client_languages_old',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_themes',
            new_name='client_themes_old',
        ),
    ]
