# Generated by Django 5.2.4 on 2026-01-14 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_delete_clientnavbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNavbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_unique', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_navbar_rel', to='mysite.client', to_field='client_id')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_navbar_rel', to='mysite.page', to_field='page_id')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_comp_unique', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.clientnavbar', to_field='comp_unique')),
            ],
            options={
                'verbose_name': '01-03 Client Navbar item',
                'ordering': ['client', 'order'],
                'unique_together': {('client', 'page')},
            },
        ),
    ]
