# Generated by Django 5.2.4 on 2025-09-11 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_rename_client_languages_client_client_languages_old_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, to='mysite.client')),
                ('id_language', models.ForeignKey(db_column='id_language', on_delete=django.db.models.deletion.CASCADE, to='mysite.language')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('id_client', 'id_language')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='client_languages_new',
            field=models.ManyToManyField(related_name='clients_new', through='mysite.ClientLanguage', to='mysite.language'),
        ),
        migrations.CreateModel(
            name='ClientTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, to='mysite.client')),
                ('id_theme', models.ForeignKey(db_column='id_theme', on_delete=django.db.models.deletion.CASCADE, to='mysite.theme')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('id_client', 'id_theme')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='client_themes_new',
            field=models.ManyToManyField(related_name='clients_new', through='mysite.ClientTheme', to='mysite.theme'),
        ),
    ]
