# Generated by Django 5.2.4 on 2026-01-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_clientnavbar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientNavbar2',
        ),
    ]
