# Generated by Django 5.2.4 on 2026-04-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_component_card_body_class_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['client_id'], 'permissions': [('view_client_data', 'Can view client data'), ('edit_client_data', 'Can edit client data'), ('create_client_data', 'Can create client data'), ('admin_client_data', 'Can admin client — manage users')], 'verbose_name': '00-03 Client'},
        ),
    ]
