# Generated by Django 5.2.4 on 2026-02-15 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_comptextblock_order_alter_gentextblock_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StbItemValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stext', models.CharField(blank=True, max_length=255, null=True)),
                ('ltext', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.language')),
                ('textstbitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.textstbitem')),
            ],
            options={
                'verbose_name': '01-06c Svg Text Badge(STB) Item value',
                'unique_together': {('textstbitem', 'language')},
            },
        ),
    ]
