# Generated by Django 5.2.4 on 2025-09-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_clientlanguage_client_client_languages_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_languages_new',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_themes_new',
        ),
        migrations.AddField(
            model_name='client',
            name='client_languages',
            field=models.ManyToManyField(related_name='clients', through='mysite.ClientLanguage', to='mysite.language'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_themes',
            field=models.ManyToManyField(related_name='clients', through='mysite.ClientTheme', to='mysite.theme'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_languages_old',
            field=models.ManyToManyField(blank=True, related_name='clients_old', to='mysite.language'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_themes_old',
            field=models.ManyToManyField(blank=True, related_name='clients_old', to='mysite.theme'),
        ),
    ]
