# Generated by Django 5.2.4 on 2026-02-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_stbitemvalue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StbItemValue',
            new_name='SvgtextbadgeValue',
        ),
    ]
