# Generated by Django 5.2.4 on 2026-01-17 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_delete_clientnavbar2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_unique', models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_page', to='mysite.client', to_field='client_id')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_page', to='mysite.page', to_field='page_id')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.clientpage')),
            ],
            options={
                'verbose_name': '01-03 Client Pages',
                'ordering': ['client', 'order'],
                'unique_together': {('client', 'page')},
            },
        ),
    ]
