# Generated by Django 5.2.4 on 2026-04-08 10:59

import django.db.models.deletion
import mysite.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_alter_client_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', mysite.models.LowercaseCharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('store', 'Store'), ('branch', 'Branch'), ('warehouse', 'Warehouse'), ('office', 'Office')], default='store', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='mysite.client')),
            ],
            options={
                'ordering': ['client', 'location_id'],
                'unique_together': {('client', 'location_id')},
            },
        ),
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', mysite.models.LowercaseCharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Client Admin'), ('staff', 'Client Staff'), ('viewer', 'Client Viewer')], default='staff', max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='mysite.client')),
                ('locations', models.ManyToManyField(blank=True, help_text='Leave empty to grant access to all locations', related_name='groups', to='mysite.clientlocation')),
            ],
            options={
                'ordering': ['client', 'group_id'],
                'unique_together': {('client', 'group_id')},
            },
        ),
        migrations.CreateModel(
            name='ClientGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('cms', 'CMS (Pages, Themes)'), ('cart', 'Shopping Cart'), ('quotation', 'Quotations'), ('order', 'Orders'), ('delivery', 'Delivery'), ('shipment', 'Shipments'), ('billing', 'Billing')], max_length=30)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete')], max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='mysite.clientgroup')),
            ],
            options={
                'ordering': ['group', 'module', 'action'],
                'unique_together': {('group', 'module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='ClientUserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='mysite.clientgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group__client', 'user'],
                'unique_together': {('user', 'group')},
            },
        ),
    ]
