# Generated by Django 5.2.4 on 2026-02-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mysite', '0012_rename_stbitemvalue_svgtextbadgevalue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='textstbitem',
            unique_together={('content_type', 'object_id', 'item_id', 'order')},
        ),
        migrations.AddIndex(
            model_name='comptextblock',
            index=models.Index(fields=['content_type', 'object_id'], name='mysite_comp_content_8337a2_idx'),
        ),
        migrations.AddIndex(
            model_name='gentextblock',
            index=models.Index(fields=['content_type', 'object_id'], name='mysite_gent_content_4f86bd_idx'),
        ),
        migrations.AddIndex(
            model_name='textstbitem',
            index=models.Index(fields=['content_type', 'object_id'], name='mysite_text_content_5b3e70_idx'),
        ),
    ]
