# Generated by Django 5.2.4 on 2026-01-19 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_clientpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('herocontent_css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('overlay', models.BooleanField(default=False)),
                ('overlay_style', models.CharField(blank=True, max_length=255, null=True)),
                ('comp_unique', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heros', to='mysite.client', to_field='client_id')),
            ],
            options={
                'verbose_name': '01-05 Hero Structure',
                'ordering': ['client', 'sitestructure'],
            },
        ),
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.CharField(choices=[('text', 'Text'), ('figure', 'Figure'), ('card', 'Card')], max_length=10)),
                ('order', models.PositiveIntegerField(default=1)),
                ('hidden', models.BooleanField(default=False)),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('comp_unique', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('card_id', models.PositiveIntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herocontents', to='mysite.client', to_field='client_id')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herocontents', to='mysite.hero')),
            ],
            options={
                'verbose_name': '01-05b Hero Content',
                'ordering': ['client', 'hero'],
            },
        ),
        migrations.CreateModel(
            name='HeroFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure_class', models.CharField(blank=True, max_length=255, null=True)),
                ('position_id', models.CharField(choices=[('start', 'Start'), ('end', 'End')], max_length=20)),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herofigures', to='mysite.client', to_field='client_id')),
                ('herocontent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='herofigures', to='mysite.herocontent')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heroimages', to='mysite.imagestatic')),
            ],
            options={
                'verbose_name': '01-05ba Hero Content Figure',
                'ordering': ['client', 'herocontent'],
            },
        ),
        migrations.CreateModel(
            name='HeroText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_class', models.CharField(blank=True, max_length=255, null=True)),
                ('title_stb_ids', models.JSONField(default=list)),
                ('contents_class', models.CharField(blank=True, max_length=255, null=True)),
                ('contents_stb_ids', models.JSONField(default=list)),
                ('actions_class', models.CharField(blank=True, max_length=255, null=True)),
                ('actions_position_id', models.CharField(choices=[('start', 'Start'), ('end', 'End')], max_length=20)),
                ('button01_class', models.CharField(blank=True, max_length=255, null=True)),
                ('button01_stb_ids', models.JSONField(default=list)),
                ('button02_class', models.CharField(blank=True, max_length=255, null=True)),
                ('button02_stb_ids', models.JSONField(default=list)),
                ('button03_class', models.CharField(blank=True, max_length=255, null=True)),
                ('button03_stb_ids', models.JSONField(default=list)),
                ('button04_class', models.CharField(blank=True, max_length=255, null=True)),
                ('button04_stb_ids', models.JSONField(default=list)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herotexts', to='mysite.client', to_field='client_id')),
                ('herocontent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='herotexts', to='mysite.herocontent')),
            ],
            options={
                'verbose_name': '01-05bc Hero Content Text',
                'ordering': ['client', 'herocontent'],
            },
        ),
        migrations.CreateModel(
            name='SiteStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shell_id', models.CharField(max_length=5)),
                ('order', models.PositiveIntegerField(default=1)),
                ('comp_unique', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('type_id', models.CharField(blank=True, choices=[('hero', 'hero'), ('card', 'card'), ('accordion', 'accordion')], max_length=30, null=True)),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('style', models.CharField(blank=True, max_length=255, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitestructures', to='mysite.client', to_field='client_id')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitestructures', to='mysite.page', to_field='page_id')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.sitestructure')),
            ],
            options={
                'verbose_name': '01-04 Client Site Structure',
                'ordering': ['client', 'page', 'shell_id', 'order'],
                'unique_together': {('client', 'page', 'shell_id')},
            },
        ),
        migrations.AddField(
            model_name='hero',
            name='sitestructure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heros', to='mysite.sitestructure'),
        ),
        migrations.DeleteModel(
            name='ClientNavbar',
        ),
        migrations.AlterUniqueTogether(
            name='hero',
            unique_together={('client', 'sitestructure')},
        ),
    ]
