# Generated by Django 5.2.4 on 2026-04-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_clientlocation_clientgroup_clientgrouppermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientgroup',
            options={'ordering': ['client', 'group_id'], 'verbose_name': '00-04 Client Group'},
        ),
        migrations.AlterModelOptions(
            name='clientlocation',
            options={'ordering': ['client', 'location_id'], 'verbose_name': '00-05 Client Location'},
        ),
    ]
