# Generated by Django 5.2.4 on 2025-09-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_remove_client_client_languages_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_languages_old',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_themes_old',
        ),
    ]
