# Generated by Django 5.2.4 on 2025-09-15 08:25

#import django.db.models.deletion
from django.db import migrations  #, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_remove_client_client_languages_old_and_more'),
    ]

    operations = [
        # ClientLanguage renames
        migrations.RenameField(
            model_name="clientlanguage",
            old_name="id_client",
            new_name="client",
        ),
        migrations.RenameField(
            model_name="clientlanguage",
            old_name="id_language",
            new_name="language",
        ),

        # ClientTheme renames
        migrations.RenameField(
            model_name="clienttheme",
            old_name="id_client",
            new_name="client",
        ),
        migrations.RenameField(
            model_name="clienttheme",
            old_name="id_theme",
            new_name="theme",
        ),
    ]