# Generated by Django 5.2.4 on 2026-01-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_hero_herocontent_herofigure_herotext_sitestructure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herocontent',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='herocontent',
            name='client',
        ),
        migrations.RemoveField(
            model_name='herotext',
            name='herocontent',
        ),
        migrations.RemoveField(
            model_name='herofigure',
            name='herocontent',
        ),
        migrations.RemoveField(
            model_name='herofigure',
            name='client',
        ),
        migrations.RemoveField(
            model_name='herofigure',
            name='image',
        ),
        migrations.RemoveField(
            model_name='herotext',
            name='client',
        ),
        migrations.AlterUniqueTogether(
            name='sitestructure',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sitestructure',
            name='client',
        ),
        migrations.RemoveField(
            model_name='sitestructure',
            name='page',
        ),
        migrations.RemoveField(
            model_name='sitestructure',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.DeleteModel(
            name='HeroContent',
        ),
        migrations.DeleteModel(
            name='HeroFigure',
        ),
        migrations.DeleteModel(
            name='HeroText',
        ),
        migrations.DeleteModel(
            name='SiteStructure',
        ),
    ]
