# Generated by Django 5.2.4 on 2026-02-17 04:50

import mysite.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_alter_textstbitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_id',
            field=mysite.models.LowercaseCharField(db_index=True, max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_id',
            field=mysite.models.LowercaseCharField(db_index=True, max_length=50, unique=True),
        ),
    ]
