# Generated by Django 5.2.4 on 2026-01-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_remove_herocontent_hero_remove_herocontent_client_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageStatic',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='SvgStatic',
            new_name='Svg',
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '00-07 Image'},
        ),
        migrations.AlterModelOptions(
            name='svg',
            options={'verbose_name': '00-08 Svg'},
        ),
        migrations.RenameIndex(
            model_name='image',
            new_name='mysite_imag_image_i_ae4806_idx',
            old_name='mysite_imag_image_i_0c3e67_idx',
        ),
        migrations.RenameIndex(
            model_name='svg',
            new_name='mysite_svg_svg_id_0d38e5_idx',
            old_name='mysite_svgs_svg_id_de0f06_idx',
        ),
    ]
