# Generated by Django 5.2.4 on 2026-04-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_customeraddress_alter_clientusermembership_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientuserprofile',
            options={'verbose_name': '00-03-03 Client Staff Profile'},
        ),
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'ordering': ['-is_default', 'city']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['client', 'order'], 'verbose_name': '00-03-02 Page'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['order'], 'verbose_name': '00-03-01 Theme'},
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='label',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
