# Generated by Django 5.2.4 on 2026-02-17 04:57

import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mysite', '0014_alter_language_language_id_alter_theme_theme_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='textblock',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='textblock',
            name='textcontent',
        ),
        migrations.RemoveField(
            model_name='textblockitem',
            name='block',
        ),
        migrations.RemoveField(
            model_name='textcontent',
            name='content_type',
        ),
        migrations.AlterUniqueTogether(
            name='textitemvalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='textitemvalue',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='textitemvalue',
            name='language',
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=mysite.models.LowercaseCharField(db_index=True, max_length=25, unique=True),
        ),
        migrations.AddIndex(
            model_name='comptextblock',
            index=models.Index(fields=['content_type', 'object_id', 'order'], name='mysite_comp_content_a5210d_idx'),
        ),
        migrations.AddIndex(
            model_name='gentextblock',
            index=models.Index(fields=['content_type', 'object_id', 'order'], name='mysite_gent_content_042b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['client', 'order'], name='mysite_page_client__5798a6_idx'),
        ),
        migrations.DeleteModel(
            name='TextBlock',
        ),
        migrations.DeleteModel(
            name='TextBlockItem',
        ),
        migrations.DeleteModel(
            name='TextContent',
        ),
        migrations.DeleteModel(
            name='TextItemValue',
        ),
    ]
