# Generated by Django 5.2.4 on 2025-09-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_alter_clientlanguage_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientlanguage',
            old_name='client',
            new_name='id_client',
        ),
        migrations.RenameField(
            model_name='clientlanguage',
            old_name='language',
            new_name='id_language',
        ),
        migrations.RenameField(
            model_name='clienttheme',
            old_name='client',
            new_name='id_client',
        ),
        migrations.RenameField(
            model_name='clienttheme',
            old_name='theme',
            new_name='id_theme',
        ),
        migrations.AlterUniqueTogether(
            name='clientlanguage',
            unique_together={('id_client', 'id_language')},
        ),
        migrations.AlterUniqueTogether(
            name='clienttheme',
            unique_together={('id_client', 'id_theme')},
        ),
    ]
