# Generated by Django 5.2.4 on 2026-04-23 07:05

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_alter_clientuserprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', mysite.models.LowercaseCharField(max_length=10)),
                ('html', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='mysite.page')),
            ],
            options={
                'verbose_name': '00-03-02a Page Content (HTML)',
                'ordering': ['page', 'language_code'],
                'unique_together': {('page', 'language_code')},
            },
        ),
    ]
