# Generated by Django 5.2.4 on 2026-02-22 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_alter_textblock_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('primary', models.CharField(max_length=20)),
                ('secondary', models.CharField(max_length=20)),
                ('accent', models.CharField(max_length=20)),
                ('neutral', models.CharField(max_length=20)),
                ('primary_content', models.CharField(max_length=20)),
                ('secondary_content', models.CharField(max_length=20)),
                ('accent_content', models.CharField(max_length=20)),
                ('neutral_content', models.CharField(max_length=20)),
                ('base_100', models.CharField(max_length=20)),
                ('base_200', models.CharField(max_length=20)),
                ('base_300', models.CharField(max_length=20)),
                ('base_content', models.CharField(max_length=20)),
                ('success', models.CharField(max_length=20)),
                ('warning', models.CharField(max_length=20)),
                ('error', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=20)),
                ('success_content', models.CharField(max_length=20)),
                ('warning_content', models.CharField(max_length=20)),
                ('error_content', models.CharField(max_length=20)),
                ('info_content', models.CharField(max_length=20)),
                ('font_body', models.CharField(max_length=100)),
                ('font_heading', models.CharField(max_length=100)),
                ('base_font_size', models.CharField(default='16px', max_length=10)),
                ('scale_ratio', models.FloatField(default=1.2)),
                ('section_gap', models.CharField(default='4rem', max_length=10)),
                ('container_padding', models.CharField(default='1rem', max_length=10)),
                ('radius_btn', models.CharField(default='0.5rem', max_length=10)),
                ('radius_card', models.CharField(default='1rem', max_length=10)),
                ('radius_input', models.CharField(default='0.5rem', max_length=10)),
                ('shadow_sm', models.CharField(default='0 1px 2px 0 rgb(0 0 0 / 0.05)', max_length=50)),
                ('shadow_md', models.CharField(default='0 4px 6px -1px rgb(0 0 0 / 0.1)', max_length=50)),
                ('shadow_lg', models.CharField(default='0 10px 15px -3px rgb(0 0 0 / 0.1)', max_length=50)),
                ('is_system', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('overrides', models.JSONField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.client')),
                ('preset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.themepreset')),
            ],
        ),
    ]
