# Generated by Django 5.2.4 on 2026-02-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_themepreset_clienttheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themepreset',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
