# Generated by Django 5.2.4 on 2026-04-23 09:46

import mysite.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_pagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='language_code',
            field=mysite.models.LowercaseCharField(default='en', max_length=2),
        ),
    ]
