# Generated by Django 5.2.4 on 2026-02-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_alter_themepreset_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienttheme',
            old_name='preset',
            new_name='themepreset',
        ),
    ]
