# Generated by Django 5.2.4 on 2026-04-24 11:36

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_alter_pagecontent_language_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'ordering': ['page', 'language_code'], 'verbose_name': '01-02 Page Content (HTML)'},
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('header', 'Header / Appbar'), ('footer', 'Footer'), ('sidebar', 'Sidebar')], default='header', max_length=20)),
                ('nav_type', models.CharField(choices=[('page', 'Internal Page'), ('url', 'External URL'), ('anchor', 'Anchor (#section)'), ('label', 'Label only (no link)')], default='page', max_length=10)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('name', mysite.models.LowercaseCharField(max_length=100)),
                ('name_en', mysite.models.LowercaseCharField(max_length=100, null=True)),
                ('name_hi', mysite.models.LowercaseCharField(max_length=100, null=True)),
                ('name_fr', mysite.models.LowercaseCharField(max_length=100, null=True)),
                ('name_ta', mysite.models.LowercaseCharField(max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hidden', models.BooleanField(default=False)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='mysite.client')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_items', to='mysite.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.navitem')),
            ],
            options={
                'verbose_name': '00-03-03 NavItem',
                'ordering': ['client', 'location', 'order'],
                'unique_together': {('client', 'location', 'parent', 'order')},
            },
        ),
    ]
