# Generated by Django 5.2.4 on 2026-02-23 04:34

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_rename_preset_clienttheme_themepreset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layout',
            options={'ordering': ('client', 'page', 'level', 'order'), 'verbose_name': '01-04 Layout'},
        ),
        migrations.AlterField(
            model_name='clienttheme',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='mysite.client'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_id',
            field=mysite.models.LowercaseCharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='clienttheme',
            unique_together={('client', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='layout',
            unique_together={('client', 'page', 'level', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('client', 'page_id')},
        ),
    ]
