# Generated by Django 5.2.4 on 2026-04-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_alter_pagecontent_options_navitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientuserprofile',
            options={'verbose_name': '00-03-04 Client Staff Profile'},
        ),
    ]
