# Generated by Django 5.2.4 on 2026-02-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_alter_layout_options_alter_clienttheme_client_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clienttheme',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clienttheme',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clienttheme',
            name='themepreset',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.DeleteModel(
            name='ClientTheme',
        ),
        migrations.DeleteModel(
            name='ThemePreset',
        ),
    ]
