# Generated by Django 5.2.4 on 2026-04-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_alter_clientuserprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='svg_pre',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='navitem',
            name='svg_suf',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
