# Generated by Django 5.2.4 on 2026-04-29 09:44

import django.db.models.deletion
import mysite.models.base
from django.db import migrations, models

def add_postgres_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    indexes = [
        # Item base table
        """CREATE INDEX IF NOT EXISTS item_attributes_gin_idx ON mysite_item USING GIN (attributes jsonb_path_ops)""",
        """CREATE INDEX IF NOT EXISTS item_client_status_idx  ON mysite_item (client_id, status, "order")""",
        """CREATE INDEX IF NOT EXISTS item_domain_idx ON mysite_item (client_id, domain, status)""",
        ## TaxonomyNode
        """CREATE INDEX IF NOT EXISTS taxonomy_node_path_idx ON mysite_taxonomynode USING BTREE (taxonomy_id, path text_pattern_ops)""",
        ## ProductItem
        """CREATE INDEX IF NOT EXISTS productitem_attributes_gin_idx ON mysite_productitem USING GIN (attributes jsonb_path_ops)""",
        """CREATE INDEX IF NOT EXISTS productitem_sku_idx ON mysite_productitem (sku) WHERE sku != ''""",
        """CREATE INDEX IF NOT EXISTS productitem_price_idx ON mysite_productitem (price) WHERE price IS NOT NULL""",
        ## SongItem
        """CREATE INDEX IF NOT EXISTS songitem_attributes_gin_idx ON mysite_songitem USING GIN (attributes jsonb_path_ops)""",
        """CREATE INDEX IF NOT EXISTS songitem_artist_idx ON mysite_songitem (artist) WHERE artist != ''""",
        """CREATE INDEX IF NOT EXISTS songitem_album_idx ON mysite_songitem (album) WHERE album != ''""",        
        ## DocumentItem
        """CREATE INDEX IF NOT EXISTS documentitem_attributes_gin_idx ON mysite_documentitem USING GIN (attributes jsonb_path_ops)""",
        """CREATE INDEX IF NOT EXISTS documentitem_format_idx ON mysite_documentitem (format) WHERE artist != ''""",        
        ## ServiceItem
        """CREATE INDEX IF NOT EXISTS serviceitem_attributes_gin_idx ON mysite_serviceitem USING GIN (attributes jsonb_path_ops)""",
        """CREATE INDEX IF NOT EXISTS serviceitem_fulfillment_type_idx ON mysite_serviceitem (fulfillment_type) WHERE artist != ''""",        
 

    ]
    for sql in indexes:
        schema_editor.execute(sql)


def remove_postgres_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    drops = [
        'DROP INDEX IF EXISTS item_attributes_gin_idx',
        'DROP INDEX IF EXISTS item_client_status_idx',
        'DROP INDEX IF EXISTS item_domain_idx',
        'DROP INDEX IF EXISTS taxonomy_node_path_idx',
        'DROP INDEX IF EXISTS productitem_attributes_gin_idx',
        'DROP INDEX IF EXISTS productitem_sku_idx',
        'DROP INDEX IF EXISTS productitem_price_idx',
        'DROP INDEX IF EXISTS songitem_attributes_gin_idx',
        'DROP INDEX IF EXISTS songitem_artist_idx',
        'DROP INDEX IF EXISTS songitem_album_idx',    
        'DROP INDEX IF EXISTS documentitem_attributes_gin_idx',
        'DROP INDEX IF EXISTS documentitem_format_idx', 
        'DROP INDEX IF EXISTS serviceitem_attributes_gin_idx',
        'DROP INDEX IF EXISTS serviceitem_fulfillment_type_idx',                       
        # ... rest of drops
    ]
    for sql in drops:
        schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_navitem_svg_pre_navitem_svg_suf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', mysite.models.base.LowercaseCharField(db_index=True, max_length=50)),
                ('domain', models.CharField(choices=[('product', 'Physical Product'), ('digital', 'Digital Product'), ('song', 'Song / Audio'), ('document', 'Document'), ('service', 'Service'), ('generic', 'Generic')], db_index=True, default='generic', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mysite.client')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(blank=True, max_length=500)),
                ('format', models.CharField(blank=True, help_text='PDF, DOCX, EPUB etc.', max_length=20)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(blank=True, help_text='Primary language of document content', max_length=10)),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_detail', to='mysite.item')),
            ],
            options={
                'verbose_name': 'Document Detail',
            },
        ),
        migrations.CreateModel(
            name='ItemMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], db_index=True, max_length=20)),
                ('media_url', models.URLField(max_length=500)),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='mysite.item')),
            ],
            options={
                'ordering': ['item', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', mysite.models.base.LowercaseCharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='{"color": "red", "size": "XL"}')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='mysite.item')),
            ],
            options={
                'ordering': ['item', 'variant_id'],
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=12, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('track_inventory', models.BooleanField(default=False)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('weight_g', models.PositiveIntegerField(blank=True, help_text='Weight in grams', null=True)),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('care_instructions', models.TextField(blank=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='e.g. {"material":"cotton","gender":"unisex"}')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='mysite.item')),
            ],
            options={
                'verbose_name': 'Product Detail',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_location_based', models.BooleanField(default=False, help_text='Service requires physical presence')),
                ('service_area', models.CharField(blank=True, help_text='Cities or zones covered', max_length=200)),
                ('fulfillment_type', models.CharField(blank=True, choices=[('in-person', 'In Person'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=20)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_detail', to='mysite.item')),
            ],
            options={
                'verbose_name': 'Service Detail',
            },
        ),
        migrations.CreateModel(
            name='SongItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('duration_s', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('bpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('musical_key', models.CharField(blank=True, max_length=10)),
                ('genre', models.CharField(blank=True, max_length=50)),
                ('audio_url', models.URLField(blank=True, max_length=500)),
                ('preview_url', models.URLField(blank=True, help_text='30-second preview clip', max_length=500)),
                ('isrc', models.CharField(blank=True, help_text='International Standard Recording Code', max_length=20)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='song_detail', to='mysite.item')),
            ],
            options={
                'verbose_name': 'Song Detail',
            },
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', mysite.models.base.LowercaseCharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxonomies', to='mysite.client')),
            ],
            options={
                'verbose_name': 'Taxonomy',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', mysite.models.base.LowercaseCharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('path', models.CharField(db_index=True, help_text="Materialized path e.g. '001.002.003'. Auto-managed.", max_length=500)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.taxonomynode')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='mysite.taxonomy')),
            ],
            options={
                'verbose_name': 'Taxonomy Node',
                'ordering': ['taxonomy', 'path', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ItemTaxonomyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary node for this taxonomy type (used for breadcrumbs)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_mappings', to='mysite.item')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_mappings', to='mysite.taxonomynode')),
            ],
            options={
                'ordering': ['item', 'node__taxonomy', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['client', 'status', 'domain'], name='mysite_item_client__ad4d3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('client', 'item_id')},
        ),
        migrations.AlterUniqueTogether(
            name='itemvariant',
            unique_together={('item', 'variant_id')},
        ),
        migrations.AddIndex(
            model_name='taxonomy',
            index=models.Index(fields=['client', 'slug'], name='mysite_taxo_client__316aca_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomy',
            index=models.Index(fields=['client', 'is_active'], name='mysite_taxo_client__6e2cb2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxonomy',
            unique_together={('client', 'slug')},
        ),
        migrations.AddIndex(
            model_name='taxonomynode',
            index=models.Index(fields=['taxonomy', 'path'], name='mysite_taxo_taxonom_349eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomynode',
            index=models.Index(fields=['taxonomy', 'is_active', 'depth'], name='mysite_taxo_taxonom_01f088_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxonomynode',
            unique_together={('taxonomy', 'slug')},
        ),
        migrations.AddIndex(
            model_name='itemtaxonomynode',
            index=models.Index(fields=['item', 'node'], name='mysite_item_item_id_5da995_idx'),
        ),
        migrations.AddIndex(
            model_name='itemtaxonomynode',
            index=models.Index(fields=['node', 'item'], name='mysite_item_node_id_1f644b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemtaxonomynode',
            unique_together={('item', 'node')},
        ),

        migrations.RunPython(
            add_postgres_indexes,
            remove_postgres_indexes,
        ),
    ]
