# Generated by Django 5.2.4 on 2026-04-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_item_documentitem_itemmedia_itemvariant_productitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_ta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='care_instructions_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='care_instructions_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='care_instructions_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='care_instructions_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='short_description_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='short_description_hi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='short_description_ta',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='songitem',
            name='album_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='songitem',
            name='album_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='songitem',
            name='album_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='songitem',
            name='album_ta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='songitem',
            name='artist_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='songitem',
            name='artist_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='songitem',
            name='artist_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='songitem',
            name='artist_ta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='name_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='name_ta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxonomynode',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='taxonomynode',
            name='name_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='taxonomynode',
            name='name_hi',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='taxonomynode',
            name='name_ta',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
