# Generated by Django 5.2.4 on 2026-02-23 06:22

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_themepreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_id', mysite.models.LowercaseCharField(max_length=10)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hidden', models.BooleanField(default=False)),
                ('overrides', models.JSONField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='mysite.client')),
                ('themepreset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.themepreset')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['client', 'order'], name='mysite_them_client__fae9d7_idx')],
                'unique_together': {('client', 'theme_id')},
            },
        ),
    ]
