# Generated by Django 5.2.4 on 2026-04-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_item_description_en_item_description_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='description_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='description_fr',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='description_hi',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='description_ta',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
