# Generated by Django 5.2.4 on 2026-02-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptextblock',
            name='href_page',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
