# Generated by Django 5.2.4 on 2026-05-01 07:21

import django.db.models.deletion
import mysite.models.base
from django.conf import settings
from django.db import migrations, models

def add_postgres_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    indexes = [
        # Item base table
        """CREATE INDEX IF NOT EXISTS item_attributes_gin_idx ON mysite_item USING GIN (attributes jsonb_path_ops)""",
        """CREATE INDEX IF NOT EXISTS item_domain_idx ON mysite_item (client_id, domain, status)""",

        # Item base table
        """CREATE INDEX IF NOT EXISTS item_client_domain_status_idx ON mysite_item (client_id, domain, status)""",
        """CREATE INDEX IF NOT EXISTS item_client_status_order_idx ON mysite_item (client_id, status, "order")""",
        """CREATE INDEX IF NOT EXISTS item_global_item_idx ON mysite_item (global_item_id, client_id)'""",
        """CREATE INDEX IF NOT EXISTS item_gtin_idx ON mysite_item (gtin) WHERE gtin != ''""",

        # GlobalItem
        """CREATE INDEX IF NOT EXISTS globalitem_gtin_idx ON mysite_globalitem (gtin) WHERE gtin != ''""",
        """CREATE INDEX IF NOT EXISTS globalitem_gpc_idx ON mysite_globalitem (gpc_brick_code) WHERE gpc_brick_code != ''""",
        """CREATE INDEX IF NOT EXISTS globalitem_attributes_gin_idx ON mysite_globalitem USING GIN (attributes jsonb_path_ops)""",        

        ## TaxonomyNode
        """CREATE INDEX IF NOT EXISTS taxonomy_node_path_idx ON mysite_taxonomynode USING BTREE (taxonomy_id, path text_pattern_ops)""",
        """CREATE INDEX IF NOT EXISTS taxonomynode_gpc_idx ON mysite_taxonomynode (gpc_code) WHERE gpc_code != ''""",

        ## ProductItem
        """CREATE INDEX IF NOT EXISTS productitem_attributes_gin_idx ON mysite_productitem USING GIN (attributes jsonb_path_ops)""",
        """CREATE INDEX IF NOT EXISTS productitem_sku_idx ON mysite_productitem (sku) WHERE sku != ''""",
        """CREATE INDEX IF NOT EXISTS productitem_price_idx ON mysite_productitem (price) WHERE price IS NOT NULL""",


        ## SongItem
        """CREATE INDEX IF NOT EXISTS songitem_attributes_gin_idx ON mysite_songitem USING GIN (attributes jsonb_path_ops)""",
        """CREATE INDEX IF NOT EXISTS songitem_artist_idx ON mysite_songitem (artist) WHERE artist != ''""",
        """CREATE INDEX IF NOT EXISTS songitem_album_idx ON mysite_songitem (album) WHERE album != ''""",        
        ## DocumentItem
        """CREATE INDEX IF NOT EXISTS documentitem_attributes_gin_idx ON mysite_documentitem USING GIN (attributes jsonb_path_ops)""",
        """CREATE INDEX IF NOT EXISTS documentitem_format_idx ON mysite_documentitem (format) WHERE artist != ''""",        
        ## ServiceItem
        """CREATE INDEX IF NOT EXISTS serviceitem_attributes_gin_idx ON mysite_serviceitem USING GIN (attributes jsonb_path_ops)""",
        """CREATE INDEX IF NOT EXISTS serviceitem_fulfillment_type_idx ON mysite_serviceitem (fulfillment_type) WHERE artist != ''""",        
        # ItemAttributeValue — critical for faceted filter queries
        """CREATE INDEX IF NOT EXISTS itemattributevalue_lookup_idx ON mysite_itemattributevalue (attribute_type_id, predefined_value_id)""",
        """CREATE INDEX IF NOT EXISTS globalitemattributevalue_lookup_idx ON mysite_globalitemattributevalue (attribute_type_id, predefined_value_id)""",
         

    ]
    for sql in indexes:
        schema_editor.execute(sql)


def remove_postgres_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    drops = [
        'DROP INDEX IF EXISTS item_attributes_gin_idx',
        'DROP INDEX IF EXISTS item_client_status_idx',
        'DROP INDEX IF EXISTS item_domain_idx',
        'DROP INDEX IF EXISTS item_client_domain_status_idx',
        'DROP INDEX IF EXISTS item_client_status_order_idx',
        'DROP INDEX IF EXISTS item_global_item_idx',
        'DROP INDEX IF EXISTS item_gtin_idx',

        'DROP INDEX IF EXISTS globalitem_gtin_idx',
        'DROP INDEX IF EXISTS globalitem_gpc_idx',
        'DROP INDEX IF EXISTS globalitem_attributes_gin_idx',
        'DROP INDEX IF EXISTS taxonomy_node_path_idx',
        'DROP INDEX IF EXISTS taxonomynode_gpc_idx',        
        'DROP INDEX IF EXISTS productitem_attributes_gin_idx',
        'DROP INDEX IF EXISTS productitem_sku_idx',
        'DROP INDEX IF EXISTS productitem_price_idx',
        'DROP INDEX IF EXISTS songitem_attributes_gin_idx',
        'DROP INDEX IF EXISTS songitem_artist_idx',
        'DROP INDEX IF EXISTS songitem_album_idx',    
        'DROP INDEX IF EXISTS documentitem_attributes_gin_idx',
        'DROP INDEX IF EXISTS documentitem_format_idx', 
        'DROP INDEX IF EXISTS serviceitem_attributes_gin_idx',
        'DROP INDEX IF EXISTS serviceitem_fulfillment_type_idx',  
        'DROP INDEX IF EXISTS itemattributevalue_lookup_idx',
        'DROP INDEX IF EXISTS globalitemattributevalue_lookup_idx',                             
        # ... rest of drops
    ]
    for sql in drops:
        schema_editor.execute(sql)

class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_taxonomy_description_en_taxonomy_description_fr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(blank=True, db_index=True, help_text='GS1 GTIN-8/12/13/14. Globally unique product identifier.', max_length=14)),
                ('gpc_brick_code', models.CharField(blank=True, db_index=True, help_text="GS1 GPC 8-digit Brick code e.g. '10000455' for Dandruff Shampoo", max_length=8)),
                ('global_item_id', mysite.models.base.LowercaseCharField(db_index=True, max_length=100, unique=True)),
                ('domain', models.CharField(choices=[('product', 'Physical Product'), ('digital', 'Digital Product / Software'), ('song', 'Song / Audio'), ('document', 'Document / Publication'), ('service', 'Service'), ('generic', 'Generic')], db_index=True, default='generic', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_hi', models.CharField(max_length=200, null=True)),
                ('name_fr', models.CharField(max_length=200, null=True)),
                ('name_ta', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_hi', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_ta', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('country_of_origin', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('weight_g', models.PositiveIntegerField(blank=True, null=True)),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('care_instructions', models.TextField(blank=True)),
                ('care_instructions_en', models.TextField(blank=True, null=True)),
                ('care_instructions_hi', models.TextField(blank=True, null=True)),
                ('care_instructions_fr', models.TextField(blank=True, null=True)),
                ('care_instructions_ta', models.TextField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Global overflow attributes not covered by typed sub-models')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Item',
                'ordering': ['global_item_id'],
            },
        ),
        migrations.CreateModel(
            name='GlobalItemAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=500)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'Global Item Attribute Value',
            },
        ),
        migrations.CreateModel(
            name='GlobalItemTaxonomyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Global Item Taxonomy Node',
            },
        ),
        migrations.CreateModel(
            name='ItemAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=500)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'Item Attribute Value',
            },
        ),
        migrations.CreateModel(
            name='NodeAttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', mysite.models.base.LowercaseCharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_hi', models.CharField(max_length=100, null=True)),
                ('name_fr', models.CharField(max_length=100, null=True)),
                ('name_ta', models.CharField(max_length=100, null=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Yes/No'), ('select', 'Select (predefined values)'), ('multiselect', 'Multi-select')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_filterable', models.BooleanField(default=True, help_text='Show in catalogue filter sidebar')),
                ('order', models.PositiveIntegerField(default=0)),
                ('gpc_attribute_code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Node Attribute Type',
                'ordering': ['node', 'order'],
            },
        ),
        migrations.CreateModel(
            name='NodeAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', mysite.models.base.LowercaseCharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_hi', models.CharField(max_length=200, null=True)),
                ('name_fr', models.CharField(max_length=200, null=True)),
                ('name_ta', models.CharField(max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('gpc_value_code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Node Attribute Value',
                'ordering': ['attribute_type', 'order'],
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['client', 'order', 'item_id'], 'verbose_name': 'Item'},
        ),
        migrations.AlterModelOptions(
            name='itemvariant',
            options={'ordering': ['item', 'variant_id'], 'verbose_name': 'Item Variant'},
        ),
        migrations.RemoveIndex(
            model_name='taxonomynode',
            name='mysite_taxo_taxonom_349eb5_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxonomynode',
            name='mysite_taxo_taxonom_01f088_idx',
        ),
        migrations.AlterUniqueTogether(
            name='taxonomynode',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='care_instructions',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='care_instructions_en',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='care_instructions_fr',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='care_instructions_hi',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='care_instructions_ta',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='height_mm',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='length_mm',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='short_description_fr',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='short_description_hi',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='short_description_ta',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='weight_g',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='width_mm',
        ),
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='care_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='care_instructions_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='care_instructions_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='care_instructions_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='care_instructions_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gpc_brick_code',
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
        migrations.AddField(
            model_name='item',
            name='gtin',
            field=models.CharField(blank=True, db_index=True, max_length=14),
        ),
        migrations.AddField(
            model_name='item',
            name='height_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='length_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weight_g',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='width_mm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='gtin',
            field=models.CharField(blank=True, help_text='Variant-level GTIN if different from item', max_length=14),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='name_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='name_ta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='gpc_segment_code',
            field=models.CharField(blank=True, help_text="GS1 GPC Segment code e.g. '50' for Food/Beverage/Tobacco", max_length=20),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='taxonomy_type',
            field=models.CharField(choices=[('gpc', 'GS1 GPC (Segment/Family/Class/Brick)'), ('geography', 'Geography'), ('department', 'Department'), ('brand', 'Brand'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='taxonomynode',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Null = global node. Client nodes can reference global nodes as parent.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_nodes', to='mysite.client'),
        ),
        migrations.AddField(
            model_name='taxonomynode',
            name='global_node',
            field=models.ForeignKey(blank=True, help_text='Global node this client node derives from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_overrides', to='mysite.taxonomynode'),
        ),
        migrations.AddField(
            model_name='taxonomynode',
            name='gpc_code',
            field=models.CharField(blank=True, db_index=True, help_text='GS1 GPC code: Segment(2), Family(4), Class(6), or Brick(8) digits', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='format',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='documentitem',
            name='language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Null = shared item (superuser-created, usable by all clients)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mysite.client'),
        ),
        migrations.AlterField(
            model_name='item',
            name='domain',
            field=models.CharField(choices=[('product', 'Physical Product'), ('digital', 'Digital Product / Software'), ('song', 'Song / Audio'), ('document', 'Document / Publication'), ('service', 'Service'), ('generic', 'Generic')], db_index=True, default='generic', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=mysite.models.base.LowercaseCharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_ta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itemtaxonomynode',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary node for this taxonomy (used for breadcrumbs)'),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides item-level price', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='is_location_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='service_area',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='songitem',
            name='duration_s',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='songitem',
            name='isrc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='songitem',
            name='preview_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='taxonomynode',
            unique_together={('taxonomy', 'client', 'slug')},
        ),
        migrations.AddIndex(
            model_name='taxonomynode',
            index=models.Index(fields=['taxonomy', 'client', 'path'], name='mysite_taxo_taxonom_e85517_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomynode',
            index=models.Index(fields=['taxonomy', 'client', 'is_active', 'depth'], name='mysite_taxo_taxonom_86bf02_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomynode',
            index=models.Index(fields=['gpc_code'], name='mysite_taxo_gpc_cod_3cd84d_idx'),
        ),
        migrations.AddField(
            model_name='globalitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_items_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='global_item',
            field=models.ForeignKey(blank=True, help_text='Global reference item this derives from. Unset fields fall back to GlobalItem values.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_items', to='mysite.globalitem'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['client', 'status', 'order'], name='mysite_item_client__93492d_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['global_item', 'client'], name='mysite_item_global__8912d9_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['gtin'], name='mysite_item_gtin_1485a0_idx'),
        ),
        migrations.AddField(
            model_name='globalitemattributevalue',
            name='global_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='mysite.globalitem'),
        ),
        migrations.AddField(
            model_name='globalitemtaxonomynode',
            name='global_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_mappings', to='mysite.globalitem'),
        ),
        migrations.AddField(
            model_name='globalitemtaxonomynode',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_item_mappings', to='mysite.taxonomynode'),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='mysite.item'),
        ),
        migrations.AddField(
            model_name='nodeattributetype',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Null = global attribute type', null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.client'),
        ),
        migrations.AddField(
            model_name='nodeattributetype',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_types', to='mysite.taxonomynode'),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_values', to='mysite.nodeattributetype'),
        ),
        migrations.AddField(
            model_name='globalitemattributevalue',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_item_values', to='mysite.nodeattributetype'),
        ),
        migrations.AddField(
            model_name='nodeattributevalue',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_values', to='mysite.nodeattributetype'),
        ),
        migrations.AddField(
            model_name='nodeattributevalue',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Null = global value', null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.client'),
        ),
        migrations.AddField(
            model_name='itemattributevalue',
            name='predefined_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_usages', to='mysite.nodeattributevalue'),
        ),
        migrations.AddField(
            model_name='globalitemattributevalue',
            name='predefined_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_item_usages', to='mysite.nodeattributevalue'),
        ),
        migrations.AddIndex(
            model_name='globalitem',
            index=models.Index(fields=['domain', 'status'], name='mysite_glob_domain_692fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='globalitem',
            index=models.Index(fields=['gtin'], name='mysite_glob_gtin_3307c0_idx'),
        ),
        migrations.AddIndex(
            model_name='globalitem',
            index=models.Index(fields=['gpc_brick_code'], name='mysite_glob_gpc_bri_6e2db7_idx'),
        ),
        migrations.AddIndex(
            model_name='globalitem',
            index=models.Index(fields=['brand', 'status'], name='mysite_glob_brand_dc88d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='globalitemtaxonomynode',
            unique_together={('global_item', 'node')},
        ),
        migrations.AlterUniqueTogether(
            name='nodeattributetype',
            unique_together={('node', 'client', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='nodeattributevalue',
            unique_together={('attribute_type', 'client', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='itemattributevalue',
            unique_together={('item', 'attribute_type')},
        ),
        migrations.AlterUniqueTogether(
            name='globalitemattributevalue',
            unique_together={('global_item', 'attribute_type')},
        ),
        migrations.RunPython(
            add_postgres_indexes,      # ← runs on: python manage.py migrate (forward)
            remove_postgres_indexes,   # ← runs on: python manage.py migrate <app> <prev> (reverse)
        ),
    ]
