# Generated by Django 5.2.4 on 2026-03-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_comptextblock_href_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardfigure',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cardtext',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='herocardfigure',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='herocardtext',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
