# Generated by Django 5.2.4 on 2026-05-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_globalitem_globalitemattributevalue_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalitem',
            options={'ordering': ['global_item_id'], 'verbose_name': '01-05 Global Item'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['client', 'order', 'item_id'], 'verbose_name': '01-06 Item'},
        ),
        migrations.AlterModelOptions(
            name='nodeattributetype',
            options={'ordering': ['node', 'order'], 'verbose_name': '01-03 Item Node Attribute Type'},
        ),
        migrations.AlterModelOptions(
            name='nodeattributevalue',
            options={'ordering': ['attribute_type', 'order'], 'verbose_name': '01-04 Item Node Attribute Value'},
        ),
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'ordering': ['order', 'slug'], 'verbose_name': '01-01 Item Taxonomy'},
        ),
        migrations.AlterModelOptions(
            name='taxonomynode',
            options={'ordering': ['taxonomy', 'path', 'order'], 'verbose_name': '01-02 Item Taxonomy Node'},
        ),
        migrations.AlterField(
            model_name='globalitem',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='globalitem',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='globalitem',
            name='name_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='globalitem',
            name='name_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='globalitem',
            name='name_ta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='name_hi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemvariant',
            name='name_ta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nodeattributetype',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='nodeattributetype',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nodeattributetype',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nodeattributetype',
            name='name_hi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nodeattributetype',
            name='name_ta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nodeattributevalue',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='nodeattributevalue',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nodeattributevalue',
            name='name_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nodeattributevalue',
            name='name_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nodeattributevalue',
            name='name_ta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='name_hi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='name_ta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomynode',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='taxonomynode',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomynode',
            name='name_fr',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomynode',
            name='name_hi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomynode',
            name='name_ta',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
