# Generated by Django 5.2.4 on 2026-03-21 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_cardfigure_order_cardtext_order_herocardfigure_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accordion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltext', models.CharField(blank=True, max_length=50, null=True)),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('layout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accordion', to='mysite.layout')),
            ],
            options={
                'verbose_name': '01-05c Accordion',
            },
        ),
        migrations.CreateModel(
            name='AccordionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltext', models.CharField(blank=True, max_length=50, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('accordion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accordiontext', to='mysite.accordion')),
            ],
        ),
    ]
