# Generated by Django 5.2.4 on 2026-05-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_alter_globalitem_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
