# Generated by Django 5.2.4 on 2026-03-21 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_accordion_accordiontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordiontext',
            name='accordion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accordiontext', to='mysite.accordion'),
        ),
    ]
