# Generated by Django 5.2.4 on 2026-05-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_productitem_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalitem',
            name='subbrand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='subbrand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
