# Generated by Django 5.2.4 on 2026-03-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_alter_accordiontext_accordion'),
    ]

    operations = [
        migrations.AddField(
            model_name='accordion',
            name='name',
            field=models.CharField(default='myaccordion_01', max_length=25),
        ),
        migrations.AddField(
            model_name='accordion',
            name='type',
            field=models.CharField(default='radio', max_length=25),
        ),
        migrations.AddField(
            model_name='accordiontext',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='accordion',
            unique_together={('layout', 'name')},
        ),
    ]
