# Generated by Django 5.2.4 on 2026-05-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0027_globalitem_subbrand_item_subbrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalitem',
            name='subbrand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='subbrand',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
