# Generated by Django 5.2.4 on 2026-03-23 09:32

import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0027_accordion_name_accordion_type_accordiontext_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accordion',
            name='css_class',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='accordion',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='accordiontext',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='card',
            name='body_class',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='card',
            name='css_class',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='card',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='cardfigure',
            name='css_class',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='cardfigure',
            name='figure_class',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='cardfigure',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='cardtext',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='comptextblock',
            name='css_class',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='comptextblock',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='gentextblock',
            name='css_class',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='gentextblock',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='hero',
            name='css_class',
            field=models.CharField(blank=True, max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='hero',
            name='herocontent_class',
            field=models.CharField(blank=True, max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='hero',
            name='overlay_style',
            field=models.CharField(blank=True, max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='herocard',
            name='body_class',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='herocard',
            name='css_class',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='herocard',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='herocardfigure',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='herocardtext',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='herofigure',
            name='css_class',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='herofigure',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='herotext',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='layout',
            name='css_class',
            field=models.CharField(blank=True, max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='layout',
            name='style',
            field=models.CharField(blank=True, max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='page',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='svgtextbadgevalue',
            name='ltext',
            field=models.TextField(blank=True, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='svgtextbadgevalue',
            name='stext',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='textstbitem',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='theme',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='themepreset',
            name='ltext',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
    ]
