# Generated by Django 5.2.4 on 2026-05-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0028_alter_globalitem_subbrand_alter_item_subbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='country_of_origin',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
