# Generated by Django 5.2.4 on 2026-03-26 04:07

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0028_alter_accordion_css_class_alter_accordion_ltext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.CharField(choices=[('hero', 'Hero'), ('card', 'Card'), ('accordion', 'Accordion'), ('carousel', 'Carousel'), ('figure', 'Figure'), ('text', 'Text'), ('card', 'Card'), ('item', 'Item')], max_length=30)),
                ('order', models.PositiveIntegerField(default=1)),
                ('hidden', models.BooleanField(default=False)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True)),
                ('css_class', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('overlay', models.BooleanField(default=False)),
                ('overlay_style', models.CharField(blank=True, max_length=255, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('accordion_type', models.CharField(blank=True, max_length=25, null=True)),
                ('accordion_name', models.CharField(blank=True, max_length=25, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='mysite.layout')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.component')),
            ],
            options={
                'verbose_name': '01-05 Component',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', mysite.models.LowercaseCharField(max_length=10)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('order', models.PositiveIntegerField(default=0)),
                ('hidden', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages3', to='mysite.client')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.page3')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Layout3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('level', models.PositiveSmallIntegerField(choices=[(10, 'Section'), (20, 'Row'), (30, 'Col'), (40, 'Cell')])),
                ('css_class', models.CharField(blank=True, max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('style', models.CharField(blank=True, max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('hidden', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
                ('comp_id', models.CharField(blank=True, choices=[('hero', 'Comp Hero'), ('card', 'Comp Card'), ('accordion', 'Comp Accordion'), ('carousel', 'Comp Carousel')], max_length=30, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.layout3')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts3', to='mysite.page3')),
            ],
            options={
                'verbose_name': '01-04 Layout',
                'ordering': ('page', 'level', 'order'),
            },
        ),
        migrations.AddIndex(
            model_name='page3',
            index=models.Index(fields=['client', 'order'], name='mysite_page_client__ce64fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='page3',
            unique_together={('client', 'page_id')},
        ),
        migrations.AlterUniqueTogether(
            name='layout3',
            unique_together={('page', 'level', 'slug')},
        ),
    ]
