# Generated by Django 5.2.4 on 2026-03-26 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0029_component_page3_layout3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='mysite.layout3'),
        ),
    ]
