# Generated by Django 5.2.4 on 2026-03-26 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0030_alter_component_layout'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='layout3',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='layout3',
            name='page',
        ),
        migrations.RemoveField(
            model_name='layout3',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Layout3',
        ),
    ]
