# Generated by Django 5.2.4 on 2026-05-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0030_item_created_by_alter_item_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('fr', 'French'), ('ta', 'Tamil')], default='en', max_length=10),
        ),
    ]
