# Generated by Django 5.2.4 on 2026-05-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0031_client_default_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='name_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='name_ta',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
