# Generated by Django 5.2.4 on 2026-03-26 10:51

import django.db.models.deletion
import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0031_alter_layout3_unique_together_remove_layout3_page_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page3',
            options={'ordering': ['client', 'order'], 'verbose_name': '01-02 Page'},
        ),
        migrations.CreateModel(
            name='Layout3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('level', models.PositiveSmallIntegerField(choices=[(10, 'Section'), (20, 'Row'), (30, 'Col'), (40, 'Cell')])),
                ('css_class', models.CharField(blank=True, max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('style', models.CharField(blank=True, max_length=255, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('hidden', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts3', to='mysite.page3')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mysite.layout3')),
            ],
            options={
                'verbose_name': '01-03 Layout',
                'ordering': ('page', 'level', 'order'),
                'unique_together': {('page', 'level', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.CharField(choices=[('hero', 'Hero'), ('card', 'Card'), ('accordion', 'Accordion'), ('carousel', 'Carousel')], max_length=30)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('css_class', models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('overlay', models.BooleanField(default=False)),
                ('overlay_style', models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('accordion_type', models.CharField(blank=True, max_length=25, null=True)),
                ('accordion_name', models.CharField(blank=True, max_length=25, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('hidden', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('layout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='component', to='mysite.layout3')),
            ],
            options={
                'verbose_name': '01-04 Component L0',
            },
        ),
        migrations.CreateModel(
            name='ComponentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('figure', 'Figure'), ('text', 'Text')], max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('hidden', models.BooleanField(default=False)),
                ('ltext', models.CharField(blank=True, max_length=50, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('css_class', models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('figure_class', models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes])),
                ('checked', models.BooleanField(default=False)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='mysite.component')),
            ],
            options={
                'verbose_name': '01-05 Component L1 Slot',
                'ordering': ['component', 'order'],
                'unique_together': {('component', 'slot_type', 'order')},
            },
        ),
    ]
