# Generated by Django 5.2.4 on 2026-05-06 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0032_alter_navitem_name_alter_navitem_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mysite.client'),
        ),
    ]
