# Generated by Django 5.2.4 on 2026-03-27 13:52

import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0032_alter_page3_options_layout3_component_componentslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='herocontent_class',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
    ]
