# Generated by Django 5.2.4 on 2026-05-08 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0033_alter_item_client'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='globalitem',
            name='mysite_glob_brand_dc88d6_idx',
        ),
        migrations.RemoveField(
            model_name='globalitem',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='globalitem',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='globalitem',
            name='subbrand',
        ),
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='item',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='item',
            name='subbrand',
        ),
    ]
