# Generated by Django 5.2.4 on 2026-03-28 04:17

import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0033_component_herocontent_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='herocontent_class',
            new_name='hero_content_class',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='overlay',
            new_name='hero_overlay',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='overlay_style',
            new_name='hero_overlay_style',
        ),
        migrations.RenameField(
            model_name='componentslot',
            old_name='checked',
            new_name='accordion_checked',
        ),
        migrations.AddField(
            model_name='component',
            name='card_body_class',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
        migrations.AddField(
            model_name='componentslot',
            name='actions_class',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[mysite.models.no_html_tags, mysite.models.no_double_quotes]),
        ),
    ]
