# Generated by Django 5.2.4 on 2026-05-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0034_remove_globalitem_mysite_glob_brand_dc88d6_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['client'], 'verbose_name': '00-03-02 Page'},
        ),
        migrations.RemoveIndex(
            model_name='page',
            name='mysite_page_client__5798a6_idx',
        ),
        migrations.RemoveField(
            model_name='page',
            name='name',
        ),
        migrations.RemoveField(
            model_name='page',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='page',
            name='name_hi',
        ),
        migrations.RemoveField(
            model_name='page',
            name='name_ta',
        ),
        migrations.RemoveField(
            model_name='page',
            name='order',
        ),
        migrations.RemoveField(
            model_name='page',
            name='parent',
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='htmlblob',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='htmlblob_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='htmlblob_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='htmlblob_hi',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='htmlblob_ta',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['client'], name='mysite_page_client__77c493_idx'),
        ),
    ]
