# Generated by Django 5.2.4 on 2026-05-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0035_alter_page_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='htmlblob',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='htmlblob_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='htmlblob_fr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='htmlblob_hi',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='htmlblob_ta',
            field=models.TextField(null=True),
        ),
    ]
