# Generated by Django 5.2.4 on 2026-05-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0036_alter_pagecontent_htmlblob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitem',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='name_hi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='name_ta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='htmlblob',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='htmlblob_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='htmlblob_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='htmlblob_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='htmlblob_ta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
