# Generated by Django 5.2.4 on 2026-05-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0037_alter_navitem_name_alter_navitem_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'ordering': ['page'], 'verbose_name': '01-02 Page Content (HTML)'},
        ),
        migrations.AlterUniqueTogether(
            name='pagecontent',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='pagecontent',
            index=models.Index(fields=['page'], name='mysite_page_page_id_d8fd47_idx'),
        ),
        migrations.RemoveField(
            model_name='pagecontent',
            name='html',
        ),
        migrations.RemoveField(
            model_name='pagecontent',
            name='language_code',
        ),
    ]
