# Generated by Django 5.2.4 on 2026-05-11 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0038_alter_pagecontent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(choices=[('catalogue_filter_sidebar', 'Catalogue: Filter Sidebar'), ('catalogue_item_card', 'Catalogue: Item Card'), ('catalogue_item_detail', 'Catalogue: Item Detail'), ('catalogue_items_list', 'Catalogue: Items List'), ('catalogue_pagination', 'Catalogue: Pagination'), ('navbar', 'Navbar'), ('footer', 'Footer')], help_text='Which template this overrides', max_length=50)),
                ('htmlblob', models.TextField(blank=True, help_text='Django template HTML. Has access to all context variables.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='mysite.client')),
            ],
            options={
                'verbose_name': 'Client Template',
                'ordering': ['client', 'template_key'],
                'unique_together': {('client', 'template_key')},
            },
        ),
    ]
