# Generated by Django 5.2.4 on 2026-05-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0039_clienttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttemplate',
            name='htmlblob_en',
            field=models.TextField(blank=True, help_text='Django template HTML. Has access to all context variables.', null=True),
        ),
        migrations.AddField(
            model_name='clienttemplate',
            name='htmlblob_fr',
            field=models.TextField(blank=True, help_text='Django template HTML. Has access to all context variables.', null=True),
        ),
        migrations.AddField(
            model_name='clienttemplate',
            name='htmlblob_hi',
            field=models.TextField(blank=True, help_text='Django template HTML. Has access to all context variables.', null=True),
        ),
        migrations.AddField(
            model_name='clienttemplate',
            name='htmlblob_ta',
            field=models.TextField(blank=True, help_text='Django template HTML. Has access to all context variables.', null=True),
        ),
    ]
