# Generated by Django 5.2.4 on 2026-05-11 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0040_clienttemplate_htmlblob_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inherit_global_media',
            field=models.BooleanField(default=True, help_text="If true, GlobalItem media is inherited and merged with this item's own media records. Item media shown first, then global media (excluding types already covered by item media)."),
        ),
        migrations.AddField(
            model_name='itemmedia',
            name='text_content',
            field=models.JSONField(blank=True, default=list, help_text="For media_type='text' only. Structure: [{title, children: [{subtitle, content: [para...]}]}]"),
        ),
        migrations.AddField(
            model_name='itemmedia',
            name='text_content_en',
            field=models.JSONField(blank=True, default=list, help_text="For media_type='text' only. Structure: [{title, children: [{subtitle, content: [para...]}]}]", null=True),
        ),
        migrations.AddField(
            model_name='itemmedia',
            name='text_content_fr',
            field=models.JSONField(blank=True, default=list, help_text="For media_type='text' only. Structure: [{title, children: [{subtitle, content: [para...]}]}]", null=True),
        ),
        migrations.AddField(
            model_name='itemmedia',
            name='text_content_hi',
            field=models.JSONField(blank=True, default=list, help_text="For media_type='text' only. Structure: [{title, children: [{subtitle, content: [para...]}]}]", null=True),
        ),
        migrations.AddField(
            model_name='itemmedia',
            name='text_content_ta',
            field=models.JSONField(blank=True, default=list, help_text="For media_type='text' only. Structure: [{title, children: [{subtitle, content: [para...]}]}]", null=True),
        ),
        migrations.AlterField(
            model_name='itemmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('pdf', 'PDF Document'), ('text', 'Structured Text')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='GlobalItemMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('pdf', 'PDF Document'), ('text', 'Structured Text')], db_index=True, max_length=20)),
                ('media_url', models.URLField(blank=True, help_text='URL for image/audio/video/pdf', max_length=500)),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('text_content', models.JSONField(blank=True, default=list, help_text='Structured text: [{title, children: [{subtitle, content: [para...]}]}]')),
                ('text_content_en', models.JSONField(blank=True, default=list, help_text='Structured text: [{title, children: [{subtitle, content: [para...]}]}]', null=True)),
                ('text_content_hi', models.JSONField(blank=True, default=list, help_text='Structured text: [{title, children: [{subtitle, content: [para...]}]}]', null=True)),
                ('text_content_fr', models.JSONField(blank=True, default=list, help_text='Structured text: [{title, children: [{subtitle, content: [para...]}]}]', null=True)),
                ('text_content_ta', models.JSONField(blank=True, default=list, help_text='Structured text: [{title, children: [{subtitle, content: [para...]}]}]', null=True)),
                ('global_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='mysite.globalitem')),
            ],
            options={
                'verbose_name': 'Global Item Media',
                'ordering': ['global_item', 'order'],
            },
        ),
    ]
