# Generated by Django 5.2.4 on 2026-05-14 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0041_item_inherit_global_media_itemmedia_text_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContentHtml',
            fields=[
            ],
            options={
                'verbose_name': '00-03C Client Content Html',
                'verbose_name_plural': '00-03C Client Content Html',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mysite.client',),
        ),
        migrations.CreateModel(
            name='ClientContentStructured',
            fields=[
            ],
            options={
                'verbose_name': '00-03B Client Content Structured',
                'verbose_name_plural': '00-03B Client Content Structured',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mysite.client',),
        ),
        migrations.CreateModel(
            name='ClientStaff',
            fields=[
            ],
            options={
                'verbose_name': '00-03E Client Staff',
                'verbose_name_plural': '00-03E Client Staff',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mysite.client',),
        ),
        migrations.CreateModel(
            name='ClientTemplatewrapper',
            fields=[
            ],
            options={
                'verbose_name': '00-03D Client Template',
                'verbose_name_plural': '00-03D Client Template',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mysite.client',),
        ),
        migrations.AlterModelOptions(
            name='clienttemplate',
            options={'ordering': ['client', 'template_key'], 'verbose_name': '00-03E Client Templates', 'verbose_name_plural': '00-03E Client Templates'},
        ),
        migrations.CreateModel(
            name='ClientBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, help_text='Leave empty to block ALL clients.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='mysite.client')),
            ],
            options={
                'verbose_name': '00-00 Client Block',
                'verbose_name_plural': '00-00 Client Blocks',
                'ordering': ['-from_date'],
                'indexes': [models.Index(fields=['is_active', 'from_date', 'to_date'], name='mysite_clie_is_acti_e20147_idx'), models.Index(fields=['client'], name='mysite_clie_client__232900_idx')],
            },
        ),
    ]
