# Generated by Django 5.2.4 on 2026-05-14 09:43

import django.db.models.deletion
import mysite.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0042_clientcontenthtml_clientcontentstructured_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='svgtextbadgevalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='svgtextbadgevalue',
            name='text',
            field=models.TextField(blank=True, validators=[mysite.models.base.no_html_tags, mysite.models.base.no_double_quotes]),
        ),
        migrations.AddField(
            model_name='svgtextbadgevalue',
            name='text_en',
            field=models.TextField(blank=True, null=True, validators=[mysite.models.base.no_html_tags, mysite.models.base.no_double_quotes]),
        ),
        migrations.AddField(
            model_name='svgtextbadgevalue',
            name='text_fr',
            field=models.TextField(blank=True, null=True, validators=[mysite.models.base.no_html_tags, mysite.models.base.no_double_quotes]),
        ),
        migrations.AddField(
            model_name='svgtextbadgevalue',
            name='text_hi',
            field=models.TextField(blank=True, null=True, validators=[mysite.models.base.no_html_tags, mysite.models.base.no_double_quotes]),
        ),
        migrations.AddField(
            model_name='svgtextbadgevalue',
            name='text_ta',
            field=models.TextField(blank=True, null=True, validators=[mysite.models.base.no_html_tags, mysite.models.base.no_double_quotes]),
        ),
        migrations.AlterField(
            model_name='svgtextbadgevalue',
            name='textstbitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='mysite.textstbitem'),
        ),
    ]
