# Generated by Django 5.2.4 on 2026-05-15 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0043_alter_svgtextbadgevalue_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svgtextbadgevalue',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='svgtextbadgevalue',
            name='ltext',
        ),
        migrations.RemoveField(
            model_name='svgtextbadgevalue',
            name='stext',
        ),
        migrations.AlterField(
            model_name='globalval',
            name='keyval',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='globalval',
            name='keyval_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='globalval',
            name='keyval_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='globalval',
            name='keyval_hi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='globalval',
            name='keyval_ta',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='svgtextbadgevalue',
            name='textstbitem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='value', to='mysite.textstbitem'),
        ),
    ]
