# Generated by Django 5.2.4 on 2026-05-16 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0044_remove_svgtextbadgevalue_language_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeatureControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('catalogue', 'Catalogue'), ('ecommerce', 'E-Commerce')], max_length=30)),
                ('is_disabled', models.BooleanField(default=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('message', models.TextField(blank=True, default='This feature is temporarily unavailable.')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, help_text='Empty = applies to ALL clients', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_controls', to='mysite.client')),
            ],
            options={
                'verbose_name': '00-01C Client Feature Control',
                'verbose_name_plural': '00-01C Client Feature Controls',
            },
        ),
    ]
