# Generated by Django 5.2.4 on 2026-05-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0045_clientfeaturecontrol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientblock',
            options={'ordering': ['-from_date'], 'verbose_name': '00-00A Client Block', 'verbose_name_plural': '00-00A Client Blocks'},
        ),
        migrations.AlterModelOptions(
            name='clientfeaturecontrol',
            options={'verbose_name': '00-00B Client Feature Control', 'verbose_name_plural': '00-00B Client Feature Controls'},
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemmedia',
            name='media_url',
            field=models.URLField(blank=True, help_text='URL for image/audio/video/pdf', max_length=500),
        ),
        migrations.DeleteModel(
            name='GentextBlock',
        ),
    ]
