# Generated by Django 5.2.4 on 2026-05-22 11:53

import django.db.models.deletion
from django.db import migrations, models

def add_postgres_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    indexes = [
        # Item base table - REMOVE #"" in the beginning and #"" at the end of each line
        ## ClientLocation
        """CREATE INDEX IF NOT EXISTS clientlocation_path_idx ON mysite_clientlocation (path text_pattern_ops)""",

    ]
    for sql in indexes:
        schema_editor.execute(sql)


def remove_postgres_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    drops = [
        'DROP INDEX IF EXISTS clientlocation_path_idx',   

        # ... rest of drops
    ]
    for sql in drops:
        schema_editor.execute(sql)

class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0046_alter_clientblock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlocation',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent location in the Region → Branch → Location tree. Null = root node.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mysite.clientlocation'),
        ),
        migrations.AddField(
            model_name='clientlocation',
            name='path',
            field=models.CharField(blank=True, default='', help_text='Materialized path: dot-separated PKs from root to this node. e.g. "1.4.17"', max_length=500),
        ),
        migrations.AlterField(
            model_name='clientfeaturecontrol',
            name='feature',
            field=models.CharField(choices=[('catalogue', 'Catalogue'), ('ecommerce', 'E-Commerce'), ('demand_planning', 'Demand Planning Module'), ('actuals_upload', 'Actuals Upload'), ('forecast_run', 'Run Statistical Forecast'), ('consensus_override', 'Consensus Override'), ('forecast_approval', 'Forecast Approval Workflow')], max_length=30),
        ),
        migrations.RunPython(
            add_postgres_indexes,      # ← runs on: python manage.py migrate (forward)
            remove_postgres_indexes,   # ← runs on: python manage.py migrate <app> <prev> (reverse)
        ),        
    ]
