# Generated by Django 5.2.4 on 2026-05-23 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def add_postgres_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    indexes = [
        # Item base table - REPLACE # in the beginning and # at the end of each line with ". So the line should read 3doubequote-Create - 3doublequote
        """CREATE INDEX IF NOT EXISTS planloc_path_tpo_idx ON  ON mysite_planninglocation (path text_pattern_ops)""",
        """CREATE INDEX IF NOT EXISTS plancust_path_tpo_idx ON  ON mysite_planningcustomer (path text_pattern_ops)""",
        """CREATE INDEX IF NOT EXISTS salesnode_path_tpo_idx ON  ON mysite_salesnode (path text_pattern_ops)""",

    ]

    for sql in indexes:
        schema_editor.execute(sql)


def remove_postgres_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    drops = [
        'DROP INDEX IF EXISTS planloc_path_tpo_idx',   
        'DROP INDEX IF EXISTS plancust_path_tpo_idx',
        'DROP INDEX IF EXISTS salesnode_path_tpo_idx',

        # ... rest of drops
    ]
    for sql in drops:
        schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0047_clientlocation_parent_clientlocation_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualSaleImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=512)),
                ('period_type', models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], default='month', help_text='Bucket granularity of the data in this upload.', max_length=16, verbose_name='period type')),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_log', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_sale_imports', to='mysite.client')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'actual sale import',
                'verbose_name_plural': 'actual sale imports',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanningCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, default='', editable=False, max_length=1024, verbose_name='materialized path')),
                ('code', models.CharField(max_length=64, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('customer_type', models.CharField(choices=[('real', 'Real customer'), ('group', 'Planning group')], default='real', max_length=16, verbose_name='customer type')),
                ('level_label', models.CharField(blank=True, help_text="E.g. 'Channel', 'Key Account', 'Customer'.", max_length=64, verbose_name='level label')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ERP / CRM identifier. Used during data import to match rows.', max_length=128, verbose_name='external ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_customers', to='mysite.client', verbose_name='client')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='mysite.planningcustomer', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'planning customer',
                'verbose_name_plural': 'planning customers',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='PlanningLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, default='', editable=False, max_length=1024, verbose_name='materialized path')),
                ('code', models.CharField(max_length=64, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('level_label', models.CharField(blank=True, help_text="Human label for this level, e.g. 'Region', 'Branch', 'DC'.", max_length=64, verbose_name='level label')),
                ('is_leaf', models.BooleanField(default=False, help_text='True if this node represents an actual stocking/planning point. Actuals and forecasts are stored only at leaf nodes.', verbose_name='is leaf')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_locations', to='mysite.client', verbose_name='client')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='mysite.planninglocation', verbose_name='parent location')),
            ],
            options={
                'verbose_name': 'planning location',
                'verbose_name_plural': 'planning locations',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='ActualSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], default='month', help_text='Granularity of this period bucket. All rows in one forecast run must share the same period_type.', max_length=16, verbose_name='period type')),
                ('period_start', models.DateField(help_text='First day of the period bucket (e.g. 2024-01-01 for a January month bucket, 2024-01-01 for Q1 2024, 2024-01-01 for ISO week starting Mon 1 Jan 2024).', verbose_name='period start')),
                ('period_end', models.DateField(editable=False, help_text='Last day of the period bucket (inclusive). Auto-computed from period_type + period_start. Stored for fast range queries.', verbose_name='period end')),
                ('qty', models.DecimalField(decimal_places=3, help_text='Sales quantity in base UoM.', max_digits=14, verbose_name='quantity')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, help_text="Revenue in client's base currency. Optional.", max_digits=16, null=True, verbose_name='revenue')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_sales', to='mysite.client')),
                ('item', models.ForeignKey(help_text="Must be a leaf node of the Taxonomy with slug='product_planning'.", on_delete=django.db.models.deletion.PROTECT, related_name='actual_sales', to='mysite.taxonomynode', verbose_name='item')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_sales', to='mysite.actualsaleimport')),
                ('planning_customer', models.ForeignKey(blank=True, help_text='Null means demand is not attributed to any specific customer or group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_sales', to='mysite.planningcustomer', verbose_name='planning customer')),
                ('planning_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actual_sales', to='mysite.planninglocation', verbose_name='planning location')),
            ],
            options={
                'verbose_name': 'actual sale',
                'verbose_name_plural': 'actual sales',
                'ordering': ['period_type', 'period_start', 'planning_location', 'item'],
            },
        ),
        migrations.CreateModel(
            name='SalesNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, default='', editable=False, max_length=1024, verbose_name='materialized path')),
                ('code', models.CharField(max_length=64, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('level_label', models.CharField(blank=True, help_text="E.g. 'National Manager', 'Area Manager', 'Sales Rep'.", max_length=64, verbose_name='level label')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_nodes', to='mysite.client', verbose_name='client')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='mysite.salesnode', verbose_name='parent node')),
                ('planning_location', models.ForeignKey(blank=True, help_text='The location this sales node primarily covers. Informational only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_nodes', to='mysite.planninglocation', verbose_name='planning location')),
            ],
            options={
                'verbose_name': 'sales node',
                'verbose_name_plural': 'sales nodes',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSalesAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='valid from')),
                ('valid_to', models.DateField(blank=True, help_text='Leave blank for the currently active assignment.', null=True, verbose_name='valid to')),
                ('planning_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_assignments', to='mysite.planningcustomer', verbose_name='planning customer')),
                ('sales_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_assignments', to='mysite.salesnode', verbose_name='sales node')),
            ],
            options={
                'verbose_name': 'customer sales assignment',
                'verbose_name_plural': 'customer sales assignments',
            },
        ),
        migrations.AddIndex(
            model_name='planningcustomer',
            index=models.Index(fields=['client', 'customer_type'], name='ix_plancust_client_type'),
        ),
        migrations.AlterUniqueTogether(
            name='planningcustomer',
            unique_together={('client', 'code')},
        ),
        migrations.AddIndex(
            model_name='planninglocation',
            index=models.Index(fields=['client', 'is_leaf'], name='ix_planloc_client_leaf'),
        ),
        migrations.AlterUniqueTogether(
            name='planninglocation',
            unique_together={('client', 'code')},
        ),
        migrations.AddIndex(
            model_name='actualsale',
            index=models.Index(fields=['client', 'planning_location', 'period_type', 'period_start'], name='ix_actualsale_loc_period'),
        ),
        migrations.AddIndex(
            model_name='actualsale',
            index=models.Index(fields=['client', 'item', 'period_type', 'period_start'], name='ix_actualsale_item_period'),
        ),
        migrations.AddIndex(
            model_name='actualsale',
            index=models.Index(fields=['client', 'planning_customer', 'period_type', 'period_start'], name='ix_actualsale_cust_period'),
        ),
        migrations.AddIndex(
            model_name='actualsale',
            index=models.Index(fields=['client', 'period_type', 'period_start', 'period_end'], name='ix_actualsale_period_range'),
        ),
        migrations.AlterUniqueTogether(
            name='actualsale',
            unique_together={('client', 'planning_location', 'item', 'planning_customer', 'period_type', 'period_start')},
        ),
        migrations.AlterUniqueTogether(
            name='salesnode',
            unique_together={('client', 'code')},
        ),
        migrations.AddIndex(
            model_name='customersalesassignment',
            index=models.Index(fields=['planning_customer', 'valid_from'], name='ix_custsales_cust_from'),
        ),
        migrations.AddIndex(
            model_name='customersalesassignment',
            index=models.Index(fields=['sales_node', 'valid_from'], name='ix_custsales_node_from'),
        ),
        migrations.RunPython(
            add_postgres_indexes,      # ← runs on: python manage.py migrate (forward)
            remove_postgres_indexes,   # ← runs on: python manage.py migrate <app> <prev> (reverse)
        ),        
    ]
