# Generated by Django 5.2.4 on 2026-05-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0048_actualsaleimport_planningcustomer_planninglocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningcustomer',
            name='level_label_en',
            field=models.CharField(blank=True, help_text="E.g. 'Channel', 'Key Account', 'Customer'.", max_length=64, null=True, verbose_name='level label'),
        ),
        migrations.AddField(
            model_name='planningcustomer',
            name='level_label_fr',
            field=models.CharField(blank=True, help_text="E.g. 'Channel', 'Key Account', 'Customer'.", max_length=64, null=True, verbose_name='level label'),
        ),
        migrations.AddField(
            model_name='planningcustomer',
            name='level_label_hi',
            field=models.CharField(blank=True, help_text="E.g. 'Channel', 'Key Account', 'Customer'.", max_length=64, null=True, verbose_name='level label'),
        ),
        migrations.AddField(
            model_name='planningcustomer',
            name='level_label_ta',
            field=models.CharField(blank=True, help_text="E.g. 'Channel', 'Key Account', 'Customer'.", max_length=64, null=True, verbose_name='level label'),
        ),
        migrations.AddField(
            model_name='planningcustomer',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='planningcustomer',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='planningcustomer',
            name='name_hi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='planningcustomer',
            name='name_ta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='planninglocation',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='planninglocation',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='planninglocation',
            name='name_hi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='planninglocation',
            name='name_ta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='salesnode',
            name='level_label_en',
            field=models.CharField(blank=True, help_text="E.g. 'National Manager', 'Area Manager', 'Sales Rep'.", max_length=64, null=True, verbose_name='level label'),
        ),
        migrations.AddField(
            model_name='salesnode',
            name='level_label_fr',
            field=models.CharField(blank=True, help_text="E.g. 'National Manager', 'Area Manager', 'Sales Rep'.", max_length=64, null=True, verbose_name='level label'),
        ),
        migrations.AddField(
            model_name='salesnode',
            name='level_label_hi',
            field=models.CharField(blank=True, help_text="E.g. 'National Manager', 'Area Manager', 'Sales Rep'.", max_length=64, null=True, verbose_name='level label'),
        ),
        migrations.AddField(
            model_name='salesnode',
            name='level_label_ta',
            field=models.CharField(blank=True, help_text="E.g. 'National Manager', 'Area Manager', 'Sales Rep'.", max_length=64, null=True, verbose_name='level label'),
        ),
        migrations.AddField(
            model_name='salesnode',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='salesnode',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='salesnode',
            name='name_hi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='salesnode',
            name='name_ta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='planningcustomer',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='planninglocation',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='salesnode',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
    ]
