# Generated by Django 5.2.4 on 2026-05-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0049_planningcustomer_level_label_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planninglocation',
            name='level_label_en',
            field=models.CharField(blank=True, help_text="Human label for this level, e.g. 'Region', 'Branch', 'DC'.", max_length=64, null=True, verbose_name='level label'),
        ),
        migrations.AddField(
            model_name='planninglocation',
            name='level_label_fr',
            field=models.CharField(blank=True, help_text="Human label for this level, e.g. 'Region', 'Branch', 'DC'.", max_length=64, null=True, verbose_name='level label'),
        ),
        migrations.AddField(
            model_name='planninglocation',
            name='level_label_hi',
            field=models.CharField(blank=True, help_text="Human label for this level, e.g. 'Region', 'Branch', 'DC'.", max_length=64, null=True, verbose_name='level label'),
        ),
        migrations.AddField(
            model_name='planninglocation',
            name='level_label_ta',
            field=models.CharField(blank=True, help_text="Human label for this level, e.g. 'Region', 'Branch', 'DC'.", max_length=64, null=True, verbose_name='level label'),
        ),
    ]
