# Generated by Django 5.2.4 on 2026-05-24 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0050_planninglocation_level_label_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actualsale',
            options={'ordering': ['period_type', 'period_start', 'planning_location', 'item'], 'verbose_name': '02-05 Actual Sale', 'verbose_name_plural': '02-05 Actual Sales'},
        ),
        migrations.AlterModelOptions(
            name='customersalesassignment',
            options={'verbose_name': '02-04 Customer Sales Assignment', 'verbose_name_plural': '02-04 Customer Sales Assignments'},
        ),
        migrations.AlterModelOptions(
            name='planningcustomer',
            options={'ordering': ['path'], 'verbose_name': '02-02 Planning Customer', 'verbose_name_plural': '02-02 Planning Customers'},
        ),
        migrations.AlterModelOptions(
            name='planninglocation',
            options={'ordering': ['path'], 'verbose_name': '02-01 Planning Location', 'verbose_name_plural': '02-01 Planning Locations'},
        ),
        migrations.AlterModelOptions(
            name='salesnode',
            options={'ordering': ['path'], 'verbose_name': '02-03 Sales Node', 'verbose_name_plural': '02-03 Sales Nodes'},
        ),
        migrations.AddField(
            model_name='customersalesassignment',
            name='client',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_sales_nodes', to='mysite.client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='planningcustomer',
            name='customer_type',
            field=models.CharField(choices=[('real', 'Real customer'), ('pseudo', 'Dummy customer'), ('group', 'Planning group')], default='real', help_text='Actuals and forecasts are NOT stored at group level', max_length=16, verbose_name='customer type'),
        ),
    ]
