# Generated by Django 5.2.4 on 2026-05-24 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0051_alter_actualsale_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersalesassignment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_sales_nodes', to='mysite.client', verbose_name='client'),
        ),
    ]
