# Generated by Django 5.2.4 on 2026-05-24 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0052_alter_customersalesassignment_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualsale',
            name='item',
            field=models.ForeignKey(help_text="Active item belonging to this client. Item must have status='active'.", on_delete=django.db.models.deletion.PROTECT, related_name='actual_sales', to='mysite.item', verbose_name='item'),
        ),
    ]
