# Generated by Django 5.2.4 on 2026-05-29 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0053_alter_actualsale_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualSaleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], max_length=16, verbose_name='period type')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(editable=False, verbose_name='period end')),
                ('total_qty', models.DecimalField(decimal_places=3, max_digits=16, verbose_name='total quantity')),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='total revenue')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_sale_locations', to='mysite.client')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_actuals', to='mysite.actualsaleimport')),
                ('planning_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actual_sale_locations', to='mysite.planninglocation', verbose_name='planning location')),
            ],
            options={
                'verbose_name': '02-06 Actual Sale Location',
                'verbose_name_plural': '02-06 Actual Sale Locations',
                'ordering': ['period_type', 'period_start', 'planning_location'],
                'indexes': [models.Index(fields=['client', 'planning_location', 'period_type', 'period_start'], name='ix_actualsaleloc_period')],
                'unique_together': {('client', 'planning_location', 'period_type', 'period_start')},
            },
        ),
    ]
