# Generated by Django 5.2.4 on 2026-05-29 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def add_postgres_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    indexes = [
        # Item base table - REPLACE # in the beginning and # at the end of each line with ". So the line should read 3doubequote-Create - 3doublequote
        #-- ForecastLine: fast lookup by version + period
        """CREATE INDEX IF NOT EXISTS ix_fcstline_ver ON mysite_forecastline (version_id, period_start)""",

        #-- ForecastLine: item-level time series per version
        """CREATE INDEX IF NOT EXISTS ix_fcstline_item_period ON mysite_forecastline (version_id, item_id, period_start)""",

        #-- ForecastLine: location drill-down
        """CREATE INDEX IF NOT EXISTS ix_fcstline_loc_period ON mysite_forecastline (version_id, planning_location_id, period_start)""",

        #-- ForecastAggregate: version + level + period (the primary access pattern)
        """CREATE INDEX IF NOT EXISTS ix_fcstagg_ver_level ON mysite_forecastaggregate (version_id, agg_level, period_start)""",

        #-- ForecastAccuracy: version + period for accuracy reports
        """CREATE INDEX IF NOT EXISTS ix_fcstacc_ver_period ON mysite_forecastaccuracy (version_id, period_start)""",


    ]
    for sql in indexes:
        schema_editor.execute(sql)


def remove_postgres_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    drops = [
        'DROP INDEX IF EXISTS ix_fcstline_ver', 
        'DROP INDEX IF EXISTS ix_fcstline_item_period',
        'DROP INDEX IF EXISTS ix_fcstline_loc_period',
        'DROP INDEX IF EXISTS ix_fcstagg_ver_level',
        'DROP INDEX IF EXISTS ix_fcstacc_ver_period', 
        # ... rest of drops
    ]
    for sql in drops:
        schema_editor.execute(sql)

class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0054_actualsalelocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(help_text='Human-readable label, e.g. "Jan-2025 Monthly Consensus v3".', max_length=255, verbose_name='version label')),
                ('period_type', models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], default='month', help_text='Granularity of forecast periods. Must match actuals period_type.', max_length=16, verbose_name='period type')),
                ('base_period_end', models.DateField(help_text='Last day of the last actuals period used as the forecast base. Forecast periods start the day after this date.', verbose_name='base period end')),
                ('horizon_periods', models.PositiveSmallIntegerField(default=6, help_text='Number of periods to forecast ahead (e.g. 6 months).', verbose_name='horizon periods')),
                ('engine_config', models.JSONField(blank=True, default=dict, help_text='StatsForecast model configuration. Example: {"models": ["AutoETS", "AutoARIMA"], "season_length": 12, "reconciliation": "MinTrace_ols"}', verbose_name='engine configuration')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked')], db_index=True, default='DRAFT', max_length=16, verbose_name='status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='locked at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_versions_approved', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_versions', to='mysite.client', verbose_name='client')),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='mysite.forecastversion', verbose_name='copied from')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_versions_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': '03-01 Forecast Version',
                'verbose_name_plural': '03-01 Forecast Versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_level', models.CharField(choices=[('sku', 'SKU (item level)'), ('subcategory', 'Sub-category'), ('category', 'Category'), ('location', 'Location'), ('region', 'Region'), ('customer', 'Customer'), ('channel', 'Channel'), ('total', 'Grand Total')], max_length=32, verbose_name='override level')),
                ('override_key', models.JSONField(help_text='JSON identifying what is being overridden. e.g. {"item_id": "ITEM-001"} or {"category": "Braking Systems"}', verbose_name='override key')),
                ('period_type', models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], max_length=16, verbose_name='period type')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(editable=False, verbose_name='period end')),
                ('override_qty', models.DecimalField(blank=True, decimal_places=3, help_text='Absolute quantity override. Mutually exclusive with override_pct.', max_digits=14, null=True, verbose_name='override quantity')),
                ('override_pct', models.DecimalField(blank=True, decimal_places=3, help_text='Percentage adjustment, e.g. 10.0 = +10%, -5.0 = -5%. Mutually exclusive with override_qty.', max_digits=7, null=True, verbose_name='override percentage')),
                ('disagg_method', models.CharField(choices=[('PROPORTIONAL', 'Proportional (historical share)'), ('EQUAL', 'Equal split across children'), ('CUSTOM', 'Custom weights (see OverrideSplitWeight)')], default='PROPORTIONAL', help_text='How this override is disaggregated to child levels. CUSTOM requires OverrideSplitWeight rows.', max_length=16, verbose_name='disaggregation method')),
                ('override_note', models.TextField(blank=True, help_text='Reason for override. Visible in the audit trail.', verbose_name='override note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_applied', models.BooleanField(default=False, help_text='True once the disaggregation task has pushed this override down to ForecastLine.override_qty.', verbose_name='is applied')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_overrides', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='mysite.forecastversion', verbose_name='forecast version')),
            ],
            options={
                'verbose_name': '03-04 Forecast Override',
                'verbose_name_plural': '03-04 Forecast Overrides',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], max_length=16, verbose_name='period type')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(editable=False, verbose_name='period end')),
                ('statistical_qty', models.DecimalField(decimal_places=3, help_text='Output of the statistical forecasting engine. Never edited by planners.', max_digits=14, verbose_name='statistical qty')),
                ('override_qty', models.DecimalField(blank=True, decimal_places=3, help_text='Planner consensus override. When set, this becomes final_qty.', max_digits=14, null=True, verbose_name='override qty')),
                ('forecast_level', models.CharField(blank=True, default='sku_customer_location', help_text='The aggregation level at which the statistical forecast was actually computed before disaggregation. e.g. "sku_customer_location" (atomic), "sku_location" (no customer), "location" (all items aggregated to location).', max_length=32, verbose_name='forecast level')),
                ('model_used', models.CharField(blank=True, help_text='The StatsForecast model that produced statistical_qty. e.g. "AutoETS", "CrostonSBA", "MovingAverage".', max_length=32, verbose_name='model used')),
                ('final_qty', models.DecimalField(decimal_places=3, editable=False, help_text='Agreed forecast quantity used for PO/production planning. Auto-computed: override_qty if set, else statistical_qty.', max_digits=14, verbose_name='final qty')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_lines', to='mysite.item', verbose_name='item')),
                ('planning_customer', models.ForeignKey(blank=True, help_text='Null = location-level forecast (no customer breakdown).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_lines', to='mysite.planningcustomer', verbose_name='planning customer')),
                ('planning_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_lines', to='mysite.planninglocation', verbose_name='planning location')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='mysite.forecastversion', verbose_name='forecast version')),
            ],
            options={
                'verbose_name': '03-02 Forecast Line',
                'verbose_name_plural': '03-02 Forecast Lines',
                'ordering': ['period_start', 'planning_location', 'item'],
            },
        ),
        migrations.CreateModel(
            name='ForecastAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agg_level', models.CharField(choices=[('total', 'Grand Total'), ('category', 'Product Category'), ('subcategory', 'Product Sub-category'), ('region', 'Location Region'), ('location', 'Planning Location'), ('channel', 'Sales Channel'), ('customer', 'Planning Customer')], db_index=True, max_length=32, verbose_name='aggregation level')),
                ('agg_key', models.JSONField(help_text='JSON identifying the specific node. e.g. {"category": "Braking Systems", "region": "North"}', verbose_name='aggregation key')),
                ('period_type', models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], max_length=16, verbose_name='period type')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(editable=False, verbose_name='period end')),
                ('statistical_qty', models.DecimalField(decimal_places=3, max_digits=16, verbose_name='statistical qty')),
                ('override_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True, verbose_name='override qty')),
                ('final_qty', models.DecimalField(decimal_places=3, editable=False, max_digits=16, verbose_name='final qty')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='mysite.forecastversion', verbose_name='forecast version')),
            ],
            options={
                'verbose_name': '03-03 Forecast Aggregate',
                'verbose_name_plural': '03-03 Forecast Aggregates',
                'ordering': ['agg_level', 'period_start'],
            },
        ),
        migrations.CreateModel(
            name='ForecastAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], max_length=16, verbose_name='period type')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(editable=False, verbose_name='period end')),
                ('actual_qty', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='actual qty')),
                ('forecast_qty', models.DecimalField(decimal_places=3, help_text='final_qty from ForecastLine at time of accuracy computation.', max_digits=14, verbose_name='forecast qty')),
                ('mape', models.DecimalField(blank=True, decimal_places=4, help_text='Mean Absolute Percentage Error. Null if actual_qty = 0.', max_digits=8, null=True, verbose_name='MAPE (%)')),
                ('bias', models.DecimalField(blank=True, decimal_places=4, help_text='Forecast bias percentage. Positive = over-forecast, negative = under-forecast.', max_digits=8, null=True, verbose_name='Bias (%)')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_accuracy', to='mysite.item', verbose_name='item')),
                ('planning_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_accuracy', to='mysite.planningcustomer', verbose_name='planning customer')),
                ('planning_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_accuracy', to='mysite.planninglocation', verbose_name='planning location')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuracy_records', to='mysite.forecastversion', verbose_name='forecast version')),
            ],
            options={
                'verbose_name': '03-06 Forecast Accuracy',
                'verbose_name_plural': '03-06 Forecast Accuracy Records',
                'ordering': ['period_start', 'item'],
            },
        ),
        migrations.CreateModel(
            name='OverrideSplitWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_key', models.JSONField(help_text='JSON identifying the child node receiving this weight. e.g. {"item_id": "SKU-001"} or {"location_code": "DEL"}', verbose_name='child key')),
                ('weight', models.DecimalField(decimal_places=6, help_text='Proportion of the override allocated to this child. Should sum to 1.0 across all children.', max_digits=8, verbose_name='weight')),
                ('override', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_weights', to='mysite.forecastoverride', verbose_name='override')),
            ],
            options={
                'verbose_name': '03-05 Override Split Weight',
                'verbose_name_plural': '03-05 Override Split Weights',
            },
        ),
        migrations.CreateModel(
            name='SeriesProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], max_length=16)),
                ('analysis_from', models.DateField(help_text='Start of the actuals window used for classification.')),
                ('analysis_to', models.DateField(help_text='End of the actuals window used for classification.')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('total_periods', models.PositiveSmallIntegerField(help_text='Total number of periods in the analysis window.')),
                ('nonzero_periods', models.PositiveSmallIntegerField(help_text='Number of periods with qty > 0.')),
                ('total_qty', models.DecimalField(decimal_places=3, help_text='Sum of all qty over the analysis window.', max_digits=16)),
                ('adi', models.DecimalField(blank=True, decimal_places=4, help_text='Average Demand Interval. total_periods / nonzero_periods. Null if nonzero_periods = 0.', max_digits=8, null=True, verbose_name='ADI')),
                ('cv2', models.DecimalField(blank=True, decimal_places=4, help_text='Squared Coefficient of Variation of non-zero demand quantities. (std / mean)² of non-zero qty. Null if fewer than 2 non-zero periods.', max_digits=8, null=True, verbose_name='CV²')),
                ('zero_rate', models.DecimalField(decimal_places=4, help_text='Fraction of periods with zero demand. 0.0–1.0.', max_digits=5, verbose_name='zero rate')),
                ('demand_class', models.CharField(choices=[('SMOOTH', 'Smooth — regular frequent demand'), ('ERRATIC', 'Erratic — frequent but variable quantity'), ('INTERMITTENT', 'Intermittent — sparse but stable quantity'), ('LUMPY', 'Lumpy — sparse and variable quantity'), ('INSUFFICIENT', 'Insufficient data — fewer than min_obs non-zero periods'), ('ZERO', 'Zero demand — no non-zero observations')], max_length=16, verbose_name='demand class')),
                ('recommended_strategy', models.CharField(choices=[('AUTOETS', 'AutoETS (smooth/erratic series)'), ('AUTOARIMA', 'AutoARIMA (erratic series)'), ('CROSTON', 'Croston SBA (intermittent series)'), ('AGG_LOCATION', 'Aggregate to Location level, then disaggregate'), ('AGG_ITEM', 'Aggregate to Item level (across locations)'), ('AGG_TOTAL', 'Aggregate to client total'), ('MOVING_AVG', 'Simple moving average (lumpy / low volume)'), ('MANUAL', 'Manual — no statistical forecast recommended')], max_length=16, verbose_name='recommended strategy')),
                ('override_strategy', models.CharField(blank=True, choices=[('AUTOETS', 'AutoETS (smooth/erratic series)'), ('AUTOARIMA', 'AutoARIMA (erratic series)'), ('CROSTON', 'Croston SBA (intermittent series)'), ('AGG_LOCATION', 'Aggregate to Location level, then disaggregate'), ('AGG_ITEM', 'Aggregate to Item level (across locations)'), ('AGG_TOTAL', 'Aggregate to client total'), ('MOVING_AVG', 'Simple moving average (lumpy / low volume)'), ('MANUAL', 'Manual — no statistical forecast recommended')], help_text='If set, the forecast engine uses this strategy instead of recommended_strategy. Set by a planner or superadmin.', max_length=16, verbose_name='override strategy')),
                ('override_note', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_profiles', to='mysite.client')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_profiles', to='mysite.item')),
                ('planning_customer', models.ForeignKey(blank=True, help_text='Null = location-level series (no customer breakdown).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_profiles', to='mysite.planningcustomer')),
                ('planning_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_profiles', to='mysite.planninglocation')),
            ],
            options={
                'verbose_name': '03-07 Series Profile',
                'verbose_name_plural': '03-07 Series Profiles',
                'ordering': ['item__item_id', 'planning_location__code'],
            },
        ),
        migrations.AddIndex(
            model_name='forecastversion',
            index=models.Index(fields=['client', 'status'], name='ix_fcstver_client_status'),
        ),
        migrations.AddIndex(
            model_name='forecastversion',
            index=models.Index(fields=['client', 'period_type', 'base_period_end'], name='ix_fcstver_client_period'),
        ),
        migrations.AddIndex(
            model_name='forecastoverride',
            index=models.Index(fields=['version', 'override_level', 'period_start'], name='ix_fcstovr_ver_level'),
        ),
        migrations.AddIndex(
            model_name='forecastoverride',
            index=models.Index(fields=['version', 'is_applied'], name='ix_fcstovr_ver_applied'),
        ),
        migrations.AlterUniqueTogether(
            name='forecastline',
            unique_together={('version', 'item', 'planning_customer', 'planning_location', 'period_type', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='forecastaccuracy',
            index=models.Index(fields=['version', 'period_start'], name='ix_fcastacc_ver_period'),
        ),
        migrations.AlterUniqueTogether(
            name='forecastaccuracy',
            unique_together={('version', 'item', 'planning_customer', 'planning_location', 'period_type', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='seriesprofile',
            index=models.Index(fields=['client', 'demand_class'], name='ix_seriespro_client_cls'),
        ),
        migrations.AddIndex(
            model_name='seriesprofile',
            index=models.Index(fields=['client', 'recommended_strategy'], name='ix_seriespro_client_strat'),
        ),
        migrations.AlterUniqueTogether(
            name='seriesprofile',
            unique_together={('client', 'item', 'planning_customer', 'planning_location', 'period_type')},
        ),

        migrations.RunPython(
            add_postgres_indexes,      # ← runs on: python manage.py migrate (forward)
            remove_postgres_indexes,   # ← runs on: python manage.py migrate <app> <prev> (reverse)
        ),

    ]
