# Generated by Django 5.2.4 on 2026-06-01 08:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0055_forecastversion_forecastoverride_forecastline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbcClassDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(help_text='Display and evaluation order. 1 = most important class (e.g. A).', verbose_name='rank')),
                ('label', models.CharField(help_text='Class label shown to planners. e.g. "A", "B", "Gold", "Tier1".', max_length=8, verbose_name='label')),
                ('cumulative_upper_pct', models.DecimalField(decimal_places=3, help_text='Items whose cumulative demand value share (at the level being evaluated) falls at or below this % receive this class. Must be 100.0 for the last rank. Must be strictly increasing.', max_digits=6, verbose_name='cumulative upper % (inclusive)')),
                ('description', models.CharField(blank=True, help_text='Optional description shown in reports.', max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': '03-00A ABC Class Definition',
                'verbose_name_plural': '03-00A ABC Class Definitions',
                'ordering': ['client', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='ForecastingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi_threshold', models.DecimalField(decimal_places=4, default=Decimal('1.3200'), help_text='Average Demand Interval cutoff. Series with ADI ≥ this value are INTERMITTENT or LUMPY. Syntetos-Boylan (2005) default: 1.32.', max_digits=6, verbose_name='ADI threshold')),
                ('cv2_threshold', models.DecimalField(decimal_places=4, default=Decimal('0.4900'), help_text='Squared Coefficient of Variation cutoff for non-zero demand. Series with CV² ≥ this value are ERRATIC or LUMPY. Syntetos-Boylan (2005) default: 0.49.', max_digits=6, verbose_name='CV² threshold')),
                ('min_nonzero_periods', models.PositiveSmallIntegerField(default=6, help_text='Minimum non-zero demand periods required before any statistical model is attempted. Series below this are INSUFFICIENT.', verbose_name='minimum non-zero periods')),
                ('time_horizon_steps', models.PositiveSmallIntegerField(default=2, help_text='How many coarser time periods to try in Part C when an item is LUMPY at all location and product levels.\nThe actual period types are derived automatically from the ForecastVersion.period_type:\n  period_type=month, steps=2 → tries [quarter, halfyear]\n  period_type=day,   steps=3 → tries [week, fortnight, month]\n  period_type=week,  steps=1 → tries [month]\n0 = do not try time aggregation at all.', verbose_name='time horizon steps')),
                ('evaluate_customer_grain', models.BooleanField(default=True, help_text='If True, Part A evaluation drills down to Item × Leaf Location × Planning Customer as the finest possible grain. If False, the finest grain is Item × Leaf Location.', verbose_name='evaluate customer grain')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '03-00 Forecasting Config',
                'verbose_name_plural': '03-00 Forecasting Configs',
            },
        ),
        migrations.CreateModel(
            name='SeriesLevelEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('fortnight', 'Fortnight (2 weeks)'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], help_text='The ForecastVersion base period type, not the evaluation period.', max_length=16, verbose_name='base period type')),
                ('grain', models.CharField(db_index=True, help_text='String encoding the aggregation dimension. e.g. "item_client", "item_loc_depth_2", "taxon_5_client", "item_client_quarter".', max_length=64, verbose_name='evaluation grain')),
                ('evaluation_key', models.JSONField(help_text='Identifies the specific node at this grain.', verbose_name='evaluation key')),
                ('eval_period_type', models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('fortnight', 'Fortnight (2 weeks)'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], help_text='The period type used for THIS evaluation. Equals period_type for Parts A and B. Coarser (e.g. quarter) for Part C.', max_length=16, verbose_name='evaluation period type')),
                ('analysis_from', models.DateField()),
                ('analysis_to', models.DateField()),
                ('total_periods', models.PositiveSmallIntegerField()),
                ('nonzero_periods', models.PositiveSmallIntegerField()),
                ('total_qty', models.DecimalField(decimal_places=3, max_digits=18)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('adi', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('cv2', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('zero_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('abc_class', models.CharField(blank=True, max_length=8, verbose_name='ABC class at this level')),
                ('value_share_pct_at_level', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('value_rank_at_level', models.PositiveIntegerField(blank=True, null=True)),
                ('demand_class', models.CharField(choices=[('SMOOTH', 'Smooth'), ('ERRATIC', 'Erratic'), ('INTERMITTENT', 'Intermittent'), ('LUMPY', 'Lumpy'), ('INSUFFICIENT', 'Insufficient data'), ('ZERO', 'Zero demand')], max_length=16, verbose_name='demand class')),
                ('is_accepted', models.BooleanField(db_index=True, default=False, verbose_name='accepted')),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('recommended_strategy', models.CharField(blank=True, choices=[('AUTOETS', 'AutoETS'), ('AUTOARIMA', 'AutoARIMA'), ('CROSTON', 'Croston SBA'), ('MOVING_AVG', 'Moving Average'), ('MANUAL', 'Manual')], max_length=16)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '03-06 Series Level Evaluation',
                'verbose_name_plural': '03-06 Series Level Evaluations',
                'ordering': ['item__item_id', 'grain'],
            },
        ),
        migrations.RemoveIndex(
            model_name='seriesprofile',
            name='ix_seriespro_client_cls',
        ),
        migrations.RemoveIndex(
            model_name='seriesprofile',
            name='ix_seriespro_client_strat',
        ),
        migrations.RemoveField(
            model_name='seriesprofile',
            name='demand_class',
        ),
        migrations.RemoveField(
            model_name='seriesprofile',
            name='recommended_strategy',
        ),
        migrations.AddField(
            model_name='seriesprofile',
            name='abc_class_atomic',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='seriesprofile',
            name='chosen_demand_class',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='seriesprofile',
            name='chosen_eval_period',
            field=models.CharField(blank=True, help_text='The period type used at the chosen level. May differ from period_type when time aggregation was applied.', max_length=16, verbose_name='chosen evaluation period type'),
        ),
        migrations.AddField(
            model_name='seriesprofile',
            name='chosen_grain',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='seriesprofile',
            name='chosen_strategy',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='seriesprofile',
            name='demand_class_atomic',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='seriesprofile',
            name='override_grain',
            field=models.CharField(blank=True, help_text='Planner-specified grain string. Must match a valid grain from SeriesLevelEvaluation for this item. The forecast engine reads effective_grain.', max_length=64, verbose_name='override grain'),
        ),
        migrations.AddField(
            model_name='seriesprofile',
            name='override_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seriesprofile',
            name='override_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seriesprofile',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='actualsale',
            name='period_type',
            field=models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('fortnight', 'Fortnight (2 weeks)'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], default='month', help_text='Granularity of this period bucket. All rows in one forecast run must share the same period_type.', max_length=16, verbose_name='period type'),
        ),
        migrations.AlterField(
            model_name='actualsaleimport',
            name='period_type',
            field=models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('fortnight', 'Fortnight (2 weeks)'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], default='month', help_text='Bucket granularity of the data in this upload.', max_length=16, verbose_name='period type'),
        ),
        migrations.AlterField(
            model_name='actualsalelocation',
            name='period_type',
            field=models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('fortnight', 'Fortnight (2 weeks)'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], max_length=16, verbose_name='period type'),
        ),
        migrations.AlterField(
            model_name='forecastaccuracy',
            name='period_type',
            field=models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('fortnight', 'Fortnight (2 weeks)'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], max_length=16, verbose_name='period type'),
        ),
        migrations.AlterField(
            model_name='forecastaggregate',
            name='period_type',
            field=models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('fortnight', 'Fortnight (2 weeks)'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], max_length=16, verbose_name='period type'),
        ),
        migrations.AlterField(
            model_name='forecastline',
            name='period_type',
            field=models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('fortnight', 'Fortnight (2 weeks)'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], max_length=16, verbose_name='period type'),
        ),
        migrations.AlterField(
            model_name='forecastoverride',
            name='period_type',
            field=models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('fortnight', 'Fortnight (2 weeks)'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], max_length=16, verbose_name='period type'),
        ),
        migrations.AlterField(
            model_name='forecastversion',
            name='engine_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object controlling the forecast engine. Supported keys:\n\n── MODEL SELECTION ─────────────────────────────────────────\n"models": ["AutoETS", "AutoARIMA"]\n    List of StatsForecast models to try. The engine picks the\n    best by cross-validation MAPE. Default: ["AutoETS"].\n\n"season_length": 12\n    Number of periods per seasonal cycle. Default: 12 for monthly.\n\n── RECONCILIATION ──────────────────────────────────────────\n"reconciliation": "MinTrace_ols"\n    Hierarchical reconciliation method. Options:\n    "BottomUp", "MinTrace_ols", "MinTrace_wls_struct".\n    Default: "MinTrace_ols".\n\n── DISAGGREGATION CONFLICT RESOLUTION ──────────────────────\n"disagg_conflict_resolution": "retain_lower"\n    Controls what happens when an item has its own forecast\n    at a fine grain (Part A) AND its product group also has\n    a forecast (Part B, because sibling items were LUMPY).\n    "retain_lower" (default): the finer-grain forecast wins.\n        The product-group disaggregation does not overwrite it.\n    "use_upper": the product-group disaggregation overwrites\n        all constituent items including those with their own\n        forecast. Use when you want a fully top-down plan.\n\n── FORECAST STORAGE ────────────────────────────────────────\n"store_all_level_forecasts": true\n    When true, a ForecastLine row is written for EVERY level\n    evaluated (not just the chosen one). Each row carries a\n    forecast_level tag. Enables post-run comparison without\n    re-running. Default: true. Set false to save storage.\n\n── LEVEL SELECTION OVERRIDES (run-level) ───────────────────\n"force_grain": null\n    When set to a grain string (e.g. "item_client"), ALL\n    series use this grain regardless of SeriesProfile.\n    Used for scenario runs: "what if we forecast everything\n    at client level?" Default: null (use SeriesProfile).\n\n"min_nonzero_override": null\n    Override ForecastingConfig.min_nonzero_periods for this\n    specific run. Useful for short-history pilots.\n\n── ACCURACY COMPUTATION ────────────────────────────────────\n"accuracy_lookback_periods": 6\n    How many past periods to include in ForecastAccuracy\n    computation for this version. Default: 6.\n', verbose_name='engine configuration'),
        ),
        migrations.AlterField(
            model_name='forecastversion',
            name='period_type',
            field=models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('fortnight', 'Fortnight (2 weeks)'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], default='month', help_text='Granularity of forecast periods. Must match actuals period_type.', max_length=16, verbose_name='period type'),
        ),
        migrations.AlterField(
            model_name='seriesprofile',
            name='adi',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='ADI at atomic grain'),
        ),
        migrations.AlterField(
            model_name='seriesprofile',
            name='analysis_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='seriesprofile',
            name='analysis_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='seriesprofile',
            name='cv2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='CV² at atomic grain'),
        ),
        migrations.AlterField(
            model_name='seriesprofile',
            name='nonzero_periods',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='seriesprofile',
            name='override_strategy',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='seriesprofile',
            name='period_type',
            field=models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('fortnight', 'Fortnight (2 weeks)'), ('month', 'Month'), ('bimonth', 'Bi-Monthly (2 months)'), ('quarter', 'Quarter'), ('halfyear', 'Half-Year'), ('year', 'Year')], max_length=16),
        ),
        migrations.AlterField(
            model_name='seriesprofile',
            name='planning_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_profiles', to='mysite.planningcustomer'),
        ),
        migrations.AlterField(
            model_name='seriesprofile',
            name='total_periods',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='seriesprofile',
            name='total_qty',
            field=models.DecimalField(decimal_places=3, max_digits=16),
        ),
        migrations.AlterField(
            model_name='seriesprofile',
            name='zero_rate',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AddField(
            model_name='abcclassdefinition',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abc_class_definitions', to='mysite.client', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='forecastingconfig',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forecasting_config', to='mysite.client', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='serieslevelevaluation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_level_evaluations', to='mysite.client'),
        ),
        migrations.AddField(
            model_name='serieslevelevaluation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_level_evaluations', to='mysite.item'),
        ),
        migrations.AddField(
            model_name='serieslevelevaluation',
            name='planning_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_level_evaluations', to='mysite.planningcustomer'),
        ),
        migrations.AddField(
            model_name='seriesprofile',
            name='chosen_evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_profiles', to='mysite.serieslevelevaluation', verbose_name='chosen evaluation'),
        ),
        migrations.AddIndex(
            model_name='seriesprofile',
            index=models.Index(fields=['client', 'chosen_grain'], name='ix_seriespro_grain'),
        ),
        migrations.AddIndex(
            model_name='seriesprofile',
            index=models.Index(fields=['client', 'demand_class_atomic'], name='ix_seriespro_cls'),
        ),
        migrations.AddIndex(
            model_name='seriesprofile',
            index=models.Index(fields=['client', 'abc_class_atomic'], name='ix_seriespro_abc'),
        ),
        migrations.AlterUniqueTogether(
            name='abcclassdefinition',
            unique_together={('client', 'label'), ('client', 'rank')},
        ),
        migrations.AddIndex(
            model_name='serieslevelevaluation',
            index=models.Index(fields=['client', 'grain', 'demand_class'], name='ix_sleveval_grain_cls'),
        ),
        migrations.AddIndex(
            model_name='serieslevelevaluation',
            index=models.Index(fields=['client', 'is_accepted'], name='ix_sleveval_accepted'),
        ),
        migrations.AddIndex(
            model_name='serieslevelevaluation',
            index=models.Index(fields=['client', 'item', 'is_accepted'], name='ix_sleveval_item_accepted'),
        ),
    ]
