# Generated by Django 5.2.4 on 2026-06-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0056_abcclassdefinition_forecastingconfig_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abcclassdefinition',
            options={'ordering': ['client', 'rank'], 'verbose_name': '02-11 ABC Class Definition', 'verbose_name_plural': '02-11 ABC Class Definitions'},
        ),
        migrations.AlterModelOptions(
            name='actualsaleimport',
            options={'ordering': ['-uploaded_at'], 'verbose_name': '02-07 actual sale import', 'verbose_name_plural': '02-07 actual sale imports'},
        ),
        migrations.AlterModelOptions(
            name='forecastaccuracy',
            options={'ordering': ['period_start', 'item'], 'verbose_name': '02-20 Forecast Accuracy', 'verbose_name_plural': '02-20 Forecast Accuracy Records'},
        ),
        migrations.AlterModelOptions(
            name='forecastaggregate',
            options={'ordering': ['agg_level', 'period_start'], 'verbose_name': '02-17 Forecast Aggregate', 'verbose_name_plural': '02-17 Forecast Aggregates'},
        ),
        migrations.AlterModelOptions(
            name='forecastingconfig',
            options={'verbose_name': '02-12 Forecasting Config', 'verbose_name_plural': '02-12 Forecasting Configs'},
        ),
        migrations.AlterModelOptions(
            name='forecastline',
            options={'ordering': ['period_start', 'planning_location', 'item'], 'verbose_name': '02-16 Forecast Line', 'verbose_name_plural': '02-16 Forecast Lines'},
        ),
        migrations.AlterModelOptions(
            name='forecastoverride',
            options={'ordering': ['-created_at'], 'verbose_name': '02-18 Forecast Override', 'verbose_name_plural': '02-18 Forecast Overrides'},
        ),
        migrations.AlterModelOptions(
            name='forecastversion',
            options={'ordering': ['-created_at'], 'verbose_name': '02-15 Forecast Version', 'verbose_name_plural': '02-15 Forecast Versions'},
        ),
        migrations.AlterModelOptions(
            name='overridesplitweight',
            options={'verbose_name': '02-19 Override Split Weight', 'verbose_name_plural': '02-19 Override Split Weights'},
        ),
        migrations.AlterModelOptions(
            name='serieslevelevaluation',
            options={'ordering': ['item__item_id', 'grain'], 'verbose_name': '02-13 Series Level Evaluation', 'verbose_name_plural': '02-13 Series Level Evaluations'},
        ),
        migrations.AlterModelOptions(
            name='seriesprofile',
            options={'ordering': ['item__item_id', 'planning_location__code'], 'verbose_name': '02-14 Series Profile', 'verbose_name_plural': '02-14 Series Profiles'},
        ),
        migrations.AddField(
            model_name='forecastaggregate',
            name='total_final_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Sum of ForecastLine.final_value across all constituent lines. This is the primary value figure shown to planners at aggregate level. Used as the basis for value-based override disaggregation: a planner sets a target ₹ value here; the engine converts it to qty deltas per item using each item's price_used.", max_digits=20, null=True, verbose_name='total final value'),
        ),
        migrations.AddField(
            model_name='forecastaggregate',
            name='total_override_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sum of ForecastLine.override_value for lines that have an override. Null when no overrides exist in this aggregate node.', max_digits=20, null=True, verbose_name='total override value'),
        ),
        migrations.AddField(
            model_name='forecastaggregate',
            name='total_statistical_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sum of ForecastLine.statistical_value across all constituent lines. This is the value the statistical engine produced before any overrides.', max_digits=20, null=True, verbose_name='total statistical value'),
        ),
        migrations.AddField(
            model_name='forecastaggregate',
            name='weighted_avg_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='sum(final_value) / sum(final_qty) across constituent lines. Computed by the rollup task. When a planner overrides total_final_value at this level, the engine computes: implied_qty = override_value / weighted_avg_price, then disaggregates the qty delta proportionally.', max_digits=14, null=True, verbose_name='weighted average price'),
        ),
        migrations.AddField(
            model_name='forecastline',
            name='final_value',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='final_qty × price_used. Auto-computed in save(). Used for value-based disaggregation at product hierarchy levels and for aggregate rollups shown to planners.', max_digits=18, null=True, verbose_name='final value'),
        ),
        migrations.AddField(
            model_name='forecastline',
            name='override_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='override_qty × price_used. Null when no override is set.', max_digits=18, null=True, verbose_name='override value'),
        ),
        migrations.AddField(
            model_name='forecastline',
            name='price_used',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The ItemPlanningProfile.effective_price at the time the forecast was computed. Stored for audit — price may change after the run.', max_digits=14, null=True, verbose_name='price used'),
        ),
        migrations.AddField(
            model_name='forecastline',
            name='statistical_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='statistical_qty × price_used. Computed by the forecast engine.', max_digits=18, null=True, verbose_name='statistical value'),
        ),
        migrations.AddField(
            model_name='forecastoverride',
            name='override_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Value-based override at aggregate levels. Mutually exclusive with override_qty and override_pct. Used when a planner sets a ₹ target for a product group or region. The engine converts this to a qty delta using ForecastAggregate.weighted_avg_price, then disaggregates the qty delta to constituent ForecastLine rows.', max_digits=18, null=True, verbose_name='override value (₹)'),
        ),
    ]
