# Generated by Django 5.2.4 on 2026-06-02 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0057_alter_abcclassdefinition_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPlanningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_price', models.DecimalField(decimal_places=4, help_text='Expected selling/transfer price used for value forecasts. Set by demand planners.', max_digits=14, verbose_name='standard price')),
                ('weighted_avg_price', models.DecimalField(blank=True, decimal_places=4, help_text='Computed from recent actuals: sum(revenue)/sum(qty). Auto-updated by the forecast engine before each run.', max_digits=14, null=True, verbose_name='weighted average price')),
                ('price_updated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_planning_profiles', to='mysite.client')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_profile', to='mysite.item')),
            ],
            options={
                'verbose_name': '02-07 Item Planning Profile',
                'verbose_name_plural': '02-07 Item Planning Profiles',
                'unique_together': {('client', 'item')},
            },
        ),
    ]
