# Generated by Django 5.2.4 on 2026-06-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0058_itemplanningprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastversion',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='ID of the Celery task chain currently running for this version.', max_length=255, verbose_name='celery task ID'),
        ),
        migrations.AddField(
            model_name='forecastversion',
            name='run_error',
            field=models.TextField(blank=True, help_text='Traceback if run_status=FAILED.', verbose_name='run error'),
        ),
        migrations.AddField(
            model_name='forecastversion',
            name='run_status',
            field=models.CharField(blank=True, choices=[('', 'Not started'), ('QUEUED', 'Queued'), ('PROFILING', 'Profiling series'), ('RUNNING', 'Running forecast'), ('RECONCILING', 'Reconciling'), ('AGGREGATING', 'Building aggregates'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], help_text='Granular progress state of the forecast run task. Separate from the version status workflow (DRAFT/IN_REVIEW/etc.).', max_length=16, verbose_name='run status'),
        ),
    ]
