"""
Django settings for mydj project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from .constants import PC_THEMES, PC_LANGUAGES
import os  # debug-toolbar
import sys # debug-toolbar

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ma64fm#lcnix#nm=$!gvdq8$y=+cull4rk655v!(ckm*$t6*-$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

TESTING = "test" in sys.argv or "PYTEST_VERSION" in os.environ  # debug-toolbar

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', # allauth
    'allauth', # allauth
    'allauth.account', # allauth
    'zapp', # zapp
    'tailwind', # tailwind
    'theme',  # tailwind
    'django_cotton.apps.SimpleAppConfig', # cotton
    'mysite', # mysite
]
TAILWIND_APP_NAME = 'theme'  # tailwind

#if DEBUG:  # tailwind
#    # Add django_browser_reload only in DEBUG mode
#    INSTALLED_APPS += ['django_browser_reload']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # <=== i18n
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'allauth.account.middleware.AccountMiddleware',     # allauth
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#if DEBUG:   # tailwind
#    # Add django_browser_reload middleware only in DEBUG mode
#    MIDDLEWARE += [
#        "django_browser_reload.middleware.BrowserReloadMiddleware",
#    ]

ROOT_URLCONF = 'mydj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['mydj/templates'], # cotton
        'APP_DIRS': False, # cotton  debug-toolbar expects this value to be True??
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mydj.context_processors.settings_constants', # context_processors
            ],
            "loaders": [(                   # cotton
                "django.template.loaders.cached.Loader",
                [
                    "django_cotton.cotton_loader.Loader",
                    "django.template.loaders.filesystem.Loader",
                    "django.template.loaders.app_directories.Loader",
                ],
            )],
            "builtins": [                   # cotton
                "django_cotton.templatetags.cotton"
            ],
        },
    },
]

WSGI_APPLICATION = 'mydj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True
USE_L10N = True  # Enable localization of formats (dates, numbers, etc.) ' L10N

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# django-allauth configurations # allauth
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",  # new
]

SITE_ID = 1  # allauth

ACCOUNT_EMAIL_VERIFICATION = "none"  # allauth

LOGIN_REDIRECT_URL = "/"  # allauth

LANGUAGES = [           # i18n
    ('en', 'English'),
    ('fr', 'French'),
]

# importing the constants from constants.py
# PC_NAVBAR_ITEMS = PC_NAVBAR_ITEMS 
PC_THEMES = PC_THEMES 
PC_LANGUAGES = PC_LANGUAGES


# CLASSV2 = "bg-gray-200 p-6 rounded-md flex-1 min-w-[200px]"

# debug-toolbar
INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]
TESTING = "test" in sys.argv or "PYTEST_VERSION" in os.environ

if not TESTING:
    INSTALLED_APPS = [
        *INSTALLED_APPS,
        "debug_toolbar",
    ]
    MIDDLEWARE = [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
        *MIDDLEWARE,
    ]