# ============================================================
# A. MIGRATION — add to 0001_catalogue.py after makemigrations
# Add JSONB GIN index manually (not auto-generated by Django)
# ============================================================

# In the migration file generated by makemigrations, add to operations[]:

3. Add to the indexing pattern kept in migration
# 1. Generate the migration normally
python manage.py makemigrations

# 2. Open the generated file and add the two functions
#    above the Migration class, then add RunPython at the
#    end of operations[]

# These functions live here — not imported from anywhere
def add_postgres_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    indexes = [
        # Item base table
        #""CREATE INDEX IF NOT EXISTS item_attributes_gin_idx ON mysite_item USING GIN (attributes jsonb_path_ops)#"",
        #""CREATE INDEX IF NOT EXISTS item_client_status_idx  ON mysite_item (client_id, status, "order")#"",
        #""CREATE INDEX IF NOT EXISTS item_domain_idx ON mysite_item (client_id, domain, status)#"",
        ## TaxonomyNode
        #""CREATE INDEX IF NOT EXISTS taxonomy_node_path_idx ON mysite_taxonomynode USING BTREE (taxonomy_id, path text_pattern_ops)#"",
        ## ProductItem
        #""CREATE INDEX IF NOT EXISTS productitem_attributes_gin_idx ON mysite_productitem USING GIN (attributes jsonb_path_ops)#"",
        #""CREATE INDEX IF NOT EXISTS productitem_sku_idx ON mysite_productitem (sku) WHERE sku != ''#"",
        #""CREATE INDEX IF NOT EXISTS productitem_price_idx ON mysite_productitem (price) WHERE price IS NOT NULL#"",
        ## SongItem
        #""CREATE INDEX IF NOT EXISTS songitem_attributes_gin_idx ON mysite_songitem USING GIN (attributes jsonb_path_ops)#"",
        #""CREATE INDEX IF NOT EXISTS songitem_artist_idx ON mysite_songitem (artist) WHERE artist != ''#"",
        #""CREATE INDEX IF NOT EXISTS songitem_album_idx ON mysite_songitem (album) WHERE album != ''#"",        
        ## DocumentItem
        #""CREATE INDEX IF NOT EXISTS documentitem_attributes_gin_idx ON mysite_documentitem USING GIN (attributes jsonb_path_ops)#"",
        #""CREATE INDEX IF NOT EXISTS documentitem_format_idx ON mysite_documentitem (format) WHERE artist != ''#"",        
        ## ServiceItem
        #""CREATE INDEX IF NOT EXISTS serviceitem_attributes_gin_idx ON mysite_serviceitem USING GIN (attributes jsonb_path_ops)#"",
        #""CREATE INDEX IF NOT EXISTS serviceitem_fulfillment_type_idx ON mysite_serviceitem (fulfillment_type) WHERE artist != ''#"",        
 

    ]
    for sql in indexes:
        schema_editor.execute(sql)


def remove_postgres_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    drops = [
        'DROP INDEX IF EXISTS item_attributes_gin_idx',
        'DROP INDEX IF EXISTS item_client_status_idx',
        'DROP INDEX IF EXISTS item_domain_idx',
        'DROP INDEX IF EXISTS taxonomy_node_path_idx',
        'DROP INDEX IF EXISTS productitem_attributes_gin_idx',
        'DROP INDEX IF EXISTS productitem_sku_idx',
        'DROP INDEX IF EXISTS productitem_price_idx',
        'DROP INDEX IF EXISTS songitem_attributes_gin_idx',
        'DROP INDEX IF EXISTS songitem_artist_idx',
        'DROP INDEX IF EXISTS songitem_album_idx',    
        'DROP INDEX IF EXISTS documentitem_attributes_gin_idx',
        'DROP INDEX IF EXISTS documentitem_format_idx', 
        'DROP INDEX IF EXISTS serviceitem_attributes_gin_idx',
        'DROP INDEX IF EXISTS serviceitem_fulfillment_type_idx',                       
        # ... rest of drops
    ]
    for sql in drops:
        schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        # ... all auto-generated model operations first ...

        migrations.RunPython(
            add_postgres_indexes,
            remove_postgres_indexes,
        ),
    ]

# 3. Verify it runs cleanly
python manage.py migrate

# 4. Confirm on PostgreSQL (production)
python manage.py dbshell
\d mysite_item   # should show the GIN index


"""  old method
migrations.RunSQL(
    sql='''
        CREATE INDEX IF NOT EXISTS item_attributes_gin_idx
        ON mysite_item USING GIN (attributes jsonb_path_ops);
    ''',
    reverse_sql='DROP INDEX IF EXISTS item_attributes_gin_idx;'
),
migrations.RunSQL(
    sql='''
        CREATE INDEX IF NOT EXISTS item_client_status_idx
        ON mysite_item (client_id, status, "order");
    ''',
    reverse_sql='DROP INDEX IF EXISTS item_client_status_idx;'
),
migrations.RunSQL(
    sql='''
        CREATE INDEX IF NOT EXISTS taxonomy_node_path_idx
        ON mysite_taxonomynode USING BTREE (taxonomy_id, path text_pattern_ops);
    ''',
    reverse_sql='DROP INDEX IF EXISTS taxonomy_node_path_idx;'
),
"""
# Note: text_pattern_ops is needed for path__startswith queries on PostgreSQL.
# In SQLite (dev) these RunSQL operations will fail silently — wrap in try/except
# or use a state_operations guard.


# ============================================================
# B. URLS — add to mydj/urls.py
# ============================================================

"""
# In mydj/urls.py, add inside urlpatterns:

from mysite.views.catalogue import catalogue_page, catalogue_filter, item_detail

urlpatterns += [
    path('<str:client_id>/catalogue/',
         catalogue_page,
         name='catalogue_page'),

    path('<str:client_id>/catalogue/filter/',
         catalogue_filter,
         name='catalogue_filter'),

    path('<str:client_id>/catalogue/<str:item_id>/',
         item_detail,
         name='item_detail'),
]

# Add these BEFORE the generic <str:client_id>/<str:page>/ catch-all.
"""


# ============================================================
# C. models/__init__.py — add catalogue exports
# ============================================================

"""
# Add to mysite/models/__init__.py:

from .catalogue import (
    Taxonomy,
    TaxonomyNode,
    Item,
    ItemTaxonomyNode,
    ItemImage,
    ItemVariant,
)
"""


# ============================================================
# D. translation.py — register translatable catalogue fields
# ============================================================

"""
# Add to mysite/translation.py:

from mysite.models.catalogue import Taxonomy, TaxonomyNode, Item


class TaxonomyTranslationOptions(TranslationOptions):
    fields = ('name',)

class TaxonomyNodeTranslationOptions(TranslationOptions):
    fields = ('name',)

class ItemTranslationOptions(TranslationOptions):
    fields = ('name', 'description',)


translator.register(Taxonomy,      TaxonomyTranslationOptions)
translator.register(TaxonomyNode,  TaxonomyNodeTranslationOptions)
translator.register(Item,          ItemTranslationOptions)
"""

#Run makemigrations for Translation to take effect
# ============================================================
# E. signals.py — add catalogue models to cache invalidation
# ============================================================

"""
# In mysite/signals.py, add to models_to_watch:

from mysite.models import Taxonomy, TaxonomyNode, Item

# Add to models_to_watch list:
# Taxonomy,
# TaxonomyNode,
# Item,

# Note: Catalogue items are NOT in the clientstatic cache
# (too large, filter-dependent). The taxonomy tree IS cached
# separately in catalogue_queries.get_taxonomy_tree().
# Add taxonomy tree cache invalidation:

def invalidate_taxonomy_cache(sender, instance, **kwargs):
    from mysite.models.catalogue import Taxonomy, TaxonomyNode
    from django.core.cache import cache

    if isinstance(instance, (Taxonomy, TaxonomyNode)):
        client = getattr(instance, 'client', None)
        if client:
            cache.delete_pattern(f'taxonomy_tree:{client.client_id}:*')
        else:
            # Global taxonomy — invalidate all clients
            cache.delete_pattern('taxonomy_tree:*')

post_save.connect(invalidate_taxonomy_cache, sender=Taxonomy)
post_save.connect(invalidate_taxonomy_cache, sender=TaxonomyNode)
post_delete.connect(invalidate_taxonomy_cache, sender=Taxonomy)
post_delete.connect(invalidate_taxonomy_cache, sender=TaxonomyNode)

# Note: cache.delete_pattern() requires django-redis backend.
# For LocMemCache (dev), loop through known keys instead.
"""


# ============================================================
# F. admin/catalogue.py — Django Admin
# ============================================================

"""
# mysite/admin/catalogue.py

from django.contrib import admin
from mysite.models.catalogue import (
    Taxonomy, TaxonomyNode, Item,
    ItemTaxonomyNode, ItemImage, ItemVariant
)


class TaxonomyNodeInline(admin.TabularInline):
    model       = TaxonomyNode
    extra       = 0
    fields      = ('slug', 'name', 'parent', 'order', 'is_active')
    show_change_link = True


@admin.register(Taxonomy)
class TaxonomyAdmin(admin.ModelAdmin):
    list_display  = ('slug', 'client', 'name', 'order', 'is_active')
    list_filter   = ('client', 'is_active')
    search_fields = ('slug', 'name')
    inlines       = [TaxonomyNodeInline]


@admin.register(TaxonomyNode)
class TaxonomyNodeAdmin(admin.ModelAdmin):
    list_display  = ('slug', 'taxonomy', 'parent', 'path', 'depth', 'order', 'is_active')
    list_filter   = ('taxonomy', 'is_active', 'depth')
    search_fields = ('slug', 'name', 'path')
    readonly_fields = ('path', 'depth')


class ItemTaxonomyNodeInline(admin.TabularInline):
    model       = ItemTaxonomyNode
    extra       = 1
    fields      = ('node', 'is_primary', 'order')
    autocomplete_fields = ['node']


class ItemImageInline(admin.TabularInline):
    model  = ItemImage
    extra  = 1
    fields = ('image_url', 'alt', 'order', 'is_primary')


class ItemVariantInline(admin.TabularInline):
    model  = ItemVariant
    extra  = 1
    fields = ('variant_id', 'name', 'sku', 'price', 'stock', 'is_active', 'attributes')


@admin.register(Item)
class ItemAdmin(admin.ModelAdmin):
    list_display    = ('item_id', 'client', 'name', 'status', 'order')
    list_filter     = ('client', 'status')
    search_fields   = ('item_id', 'name', 'attributes')
    readonly_fields = ('created_at', 'updated_at')
    inlines         = [ItemTaxonomyNodeInline, ItemImageInline, ItemVariantInline]
    fieldsets = (
        ('Identity', {
            'fields': ('client', 'item_id', 'status', 'order')
        }),
        ('Content', {
            'fields': ('name', 'description', 'image_url', 'image_alt')
        }),
        ('Attributes (JSONB)', {
            'fields': ('attributes',),
            'description': 'Store domain-specific fields as JSON. '
                           'For products: {"price": 999, "currency": "INR", "sku": "ABC-001"}'
        }),
        ('Timestamps', {
            'fields': ('created_at', 'updated_at'),
            'classes': ('collapse',)
        }),
    )
"""


# ============================================================
# G. SAMPLE DATA — Products as Item (management command)
# ============================================================

"""
# mysite/management/commands/load_sample_products.py

from django.core.management.base import BaseCommand
from mysite.models import Client
from mysite.models.catalogue import (
    Taxonomy, TaxonomyNode, Item, ItemTaxonomyNode
)


class Command(BaseCommand):
    help = 'Load sample product catalogue data for a client'

    def add_arguments(self, parser):
        parser.add_argument('client_id', type=str)

    def handle(self, *args, **options):
        client_id = options['client_id']
        client    = Client.objects.get(client_id=client_id)

        # ── Taxonomies ────────────────────────────────────────────
        cat_tax, _ = Taxonomy.objects.get_or_create(
            client=client, slug='category',
            defaults={'name': 'Category', 'order': 1}
        )

        # Category nodes
        apparel, _ = TaxonomyNode.objects.get_or_create(
            taxonomy=cat_tax, slug='apparel',
            defaults={'name': 'Apparel', 'order': 1, 'path': '001', 'depth': 0}
        )
        mens, _ = TaxonomyNode.objects.get_or_create(
            taxonomy=cat_tax, slug='mens',
            defaults={
                'name': "Men's", 'order': 1, 'depth': 1,
                'parent': apparel, 'path': '001.001'
            }
        )
        womens, _ = TaxonomyNode.objects.get_or_create(
            taxonomy=cat_tax, slug='womens',
            defaults={
                'name': "Women's", 'order': 2, 'depth': 1,
                'parent': apparel, 'path': '001.002'
            }
        )
        electronics, _ = TaxonomyNode.objects.get_or_create(
            taxonomy=cat_tax, slug='electronics',
            defaults={'name': 'Electronics', 'order': 2, 'path': '002', 'depth': 0}
        )

        # Geography taxonomy
        geo_tax, _ = Taxonomy.objects.get_or_create(
            client=client, slug='geography',
            defaults={'name': 'Geography', 'order': 2}
        )
        india, _ = TaxonomyNode.objects.get_or_create(
            taxonomy=geo_tax, slug='india',
            defaults={'name': 'India', 'order': 1, 'path': '001', 'depth': 0}
        )

        # ── Items ─────────────────────────────────────────────────
        products = [
            {
                'item_id':   'tshirt-001',
                'name':      'Classic Cotton T-Shirt',
                'description': 'Comfortable everyday cotton tee. Available in multiple colors.',
                'status':    'active',
                'order':     1,
                'image_url': 'https://picsum.photos/seed/tshirt/400/400',
                'image_alt': 'Classic Cotton T-Shirt',
                'attributes': {
                    'price': 599,
                    'currency': 'INR',
                    'sku': 'APP-TS-001',
                    'material': 'Cotton',
                    'weight_g': 250,
                },
                'nodes': [mens],
            },
            {
                'item_id':   'saree-001',
                'name':      'Silk Banarasi Saree',
                'description': 'Traditional Banarasi silk saree with gold zari work.',
                'status':    'active',
                'order':     2,
                'image_url': 'https://picsum.photos/seed/saree/400/400',
                'image_alt': 'Silk Banarasi Saree',
                'attributes': {
                    'price': 4999,
                    'currency': 'INR',
                    'sku': 'APP-SR-001',
                    'material': 'Silk',
                    'occasion': 'Formal',
                },
                'nodes': [womens],
            },
            {
                'item_id':   'phone-001',
                'name':      'Wireless Earbuds Pro',
                'description': 'Premium wireless earbuds with active noise cancellation.',
                'status':    'active',
                'order':     3,
                'image_url': 'https://picsum.photos/seed/earbuds/400/400',
                'image_alt': 'Wireless Earbuds Pro',
                'attributes': {
                    'price': 2499,
                    'currency': 'INR',
                    'sku': 'ELC-EB-001',
                    'battery_hours': 8,
                    'connectivity': 'Bluetooth 5.3',
                },
                'nodes': [electronics],
            },
        ]

        for p in products:
            nodes = p.pop('nodes')
            item, created = Item.objects.update_or_create(
                client=client,
                item_id=p['item_id'],
                defaults=p
            )
            for node in nodes:
                ItemTaxonomyNode.objects.get_or_create(
                    item=item, node=node,
                    defaults={'is_primary': True}
                )
            # All items belong to India geography
            ItemTaxonomyNode.objects.get_or_create(
                item=item, node=india,
                defaults={'is_primary': False}
            )
            self.stdout.write(
                f"{'Created' if created else 'Updated'}: {item.item_id}"
            )

        self.stdout.write(self.style.SUCCESS(
            f'Sample products loaded for {client_id}'
        ))
"""


# ============================================================
# H. PERFORMANCE STRATEGY NOTES
# ============================================================
"""
1. JSONB GIN index (PostgreSQL only):
   Enables fast filtering on attributes -> e.g. ?attr_color=red
   Added via RunSQL in migration (see section A above).
   Query: Item.objects.filter(attributes__color='red') uses this index.

2. Materialized path for tree queries:
   path__startswith="001.002." is a B-tree prefix scan — very fast.
   Much faster than recursive CTE for read-heavy catalogue pages.
   Trade-off: path must be recomputed on node move (rare operation).

3. N+1 prevention:
   All Item queries use select_related + prefetch_related with to_attr.
   Never call item.images.all() in a template loop — always prefetch.

4. Taxonomy tree caching:
   get_taxonomy_tree() caches per client+slug for 1 hour.
   Invalidated on TaxonomyNode post_save/post_delete signals.
   For 20k+ items, taxonomy trees are small (hundreds of nodes)
   and safe to cache in Redis.

5. Catalogue items are NOT in clientstatic cache:
   Items are filter-dependent and too numerous to cache as a flat list.
   The clientstatic cache holds structural/theme data only.
   Item queries hit the DB with proper indexes — fast enough for 20k items.

6. Pagination:
   Always paginate — never load all items. Default 24/page.
   Django Paginator with LIMIT/OFFSET. For very large datasets
   (100k+), switch to keyset pagination (WHERE id > last_id).

7. SQLite vs PostgreSQL:
   JSONB GIN index and text_pattern_ops are PostgreSQL-only.
   attributes__color filter works in SQLite without the index (slower).
   path__startswith works in SQLite without text_pattern_ops (slower).
   Dev performance is acceptable; production needs PostgreSQL.
"""